Added bxt_disable_changelevel
YaLTeR/BunnymodXT pull request #168
Opened 2021-07-24 15:52 UTC by SmileyAG

This works on Windows, but I have no idea about Linux, can someone confirm it? @chinese-soup

2021-07-24 16:17 UTC, hobokenn requested changes

2021-07-24 16:17 UTC, hobokenn commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (ORIG_CChangeLevel__ChangeLevelNow)
if (ORIG_CChangeLevel__ChangeLevelNow || ORIG_CChangeLevel__ChangeLevelNow_Linux)

2021-07-24 16:18 UTC, hobokenn commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (ORIG_CChangeLevel__ChangeLevelNow)
could you add that to SaveTouch too please?

2021-07-24 16:24 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (ORIG_CChangeLevel__ChangeLevelNow)
Done. Thanks!

2021-07-25 12:31 UTC, YaLTeR commented
On Linux the function seems to be found but bxt_disable_changelevel 1 doesn't seem to do anything.

2021-07-30 14:15 UTC, merged

2021-07-30 14:15 UTC, YaLTeR commented
Thanks