Added bxt_viewmodel_fov
YaLTeR/BunnymodXT pull request #173
Opened 2021-08-03 14:05 UTC by chinese-soup

Based on the previous OpenAG implementation, therefore same values apply, to reiterate:
- `default_fov 90` && `bxt_viewmodel_fov 0` ==> no application, FOV of weapon same as default_fov's value
- `default_fov 90` && `bxt_viewmodel_fov 90` ==> yes application, but FOV of weapon is the same as on default_fov 90
- `default_fov 90` && `bxt_viewmodel_fov 130` ==> yes application, FOV of weapon is the same as it would be with default_fov 130
etc.

**Note:**
```c++
// If the current's frame FOV is not default_fov, we are zoomed in, in that case don't override frustum
if (desired_viewmodel_fov > 0 && desired_viewmodel_fov < 179 && currentRenderFOV == CVars::default_fov.GetFloat())
```

If currentRenderFOV is never updated because of the `HUD_UpdateClientData` function not being hooked, the `bxt_viewmodel_fov` will appear but its value is never gonna apply and `ORIG_R_DrawViewModel` is just gonna get called. 
I dunno how to make it so that the Cvar only registers when both `HUD_UpdateClientData` and `R_DrawViewModel` are available since they are from two different classes. :/

**Note 2:**
Missing Windows patterns, will take a look later unless somebody else wants to. ;)

**Note 3:**
Should this be considered a cheat (bxt_ch_viewmodel_fov)?

2021-08-03 14:14 UTC, chinese-soup commented
Drafting since I forgot about the attachments. :)

2021-08-03 18:59 UTC, hobokenn commented
PATTERNS(R_DrawViewModel,
			"HL-SteamPipe",
			"55 8B EC 83 EC 50 D9 05 ?? ?? ?? ?? D8 1D ?? ?? ?? ?? 56 57 33 FF C7 45",
			"HL-4554",
			"83 EC ?? D9 05 ?? ?? ?? ?? D8 1D ?? ?? ?? ?? 56 57 33 FF C7 44"
		);
		
> If currentRenderFOV is never updated because of the HUD_UpdateClientData function not being hooked

It shouldn't be a problem because this function is always hooked, because it is exported.

2021-08-03 19:00 UTC, hobokenn commented on BunnymodXT/modules/HwDLL.hpp
> +	HOOK_DECL(void, __cdecl, R_DrawViewModel)
This should probably be int

2021-08-17 04:52 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +
ah yes it's one of our favorites again

2021-08-24 17:18 UTC, YaLTeR commented
Needs a conflict fix too

2021-08-24 18:03 UTC, chinese-soup commented
> Needs a conflict fix too

Yeah ik, it's still a draft, cuz I need to apply all (maybe except for thirdperson shell ejection since this is meant for spedrunning single player games) the fixes tmp64 made to this code.

2021-08-30 20:10 UTC, chinese-soup commented
May have fucked up the merge commit while resolving the changes a bit, but hopefully this should be alright now? I can squash now if it's needed.

2021-08-31 05:31 UTC, YaLTeR requested changes
tldr: let's try to make good commits

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +	HwDLL::GetInstance().currentRenderFOV = pcldata->fov;
Shouldn't this be after `ORIG_HUD_UpdateClientData` in case the client updates the FOV?

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +		DEF_FUTURE(R_DrawViewModel)
Could you squash this commit into previous?

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +//extern "C" void __cdecl _Z15VectorTransformPKfPA4_fPf(const vec3_t in1, float* in2, vec3_t out)
Leftover comment? Also missing newline

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +			EngineDevMsg("[client dll] [WINDOWS] Found StudioCalcAttachments at %p (using pattern %s).\n", ORIG_VectorTransform, pattern->name());
been there done that fixed in bxt-rs
> `ORIG_VectorTransform`

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +extern "C" void __cdecl _Z22EV_GetDefaultShellInfoP12event_args_sPfS1_S1_S1_S1_S1_S1_fff(event_args_t *args, float *origin, float *velocity, float *ShellVelocity, float *ShellOrigin,
Is it intended that this isn't hooked on windows?

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +	pEngfuncs->Con_Printf("forward = %f %f %f\n ", last_viewforward[0], last_viewforward[1], last_viewforward[2]);
leftover debug prints

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.hpp
> +	//HOOK_DECL(void, __cdecl, VectorTransform, const vec3_t in1, float* in2, vec3_t out)
leftover?

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +}*/
leftover?

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +		//	ORIG_studioapi_GetCurrentEntity, HOOKED_studioapi_GetCurrentEntity
leftover?

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +		int ScreenHeight = CustomHud::GetScreenInfo().iHeight;
Seems like a change that should be put into the original commit instead.

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +		auto desired_viewmodel_fov = CVars::bxt_viewmodel_fov.GetFloat();
Unused?

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +}
Leftover stuff

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/patterns.hpp
> +			"8B 44 24 ?? 8B 4C 24 ?? 8B 54 24 ?? D9 40 ??"
Don't leave ?? in the end, it's no use (bxt-rs checks for this at compile time heh)

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> -	return ClientDLL::HOOKED_StudioCalcAttachments(thisptr);
This commit sounds like it should be squashed into the corresponding previous commit

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
>  			ORIG_HUD_DrawTransparentTriangles, HOOKED_HUD_DrawTransparentTriangles,
Also candidate for squashing

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +			ORIG_EV_GetDefaultShellInfo, HOOKED_EV_GetDefaultShellInfo,
Another squashing candidate

2021-08-31 05:31 UTC, YaLTeR commented on BunnymodXT/cvars.cpp
> +	CVarWrapper bxt_force_zmax("bxt_force_zmax", "0");
Seems unrelated? Is this due to a merge commit? Better to do the rebase thing instead

2021-08-31 08:59 UTC, chinese-soup commented on BunnymodXT/modules/ClientDLL.cpp
> +extern "C" void __cdecl _Z22EV_GetDefaultShellInfoP12event_args_sPfS1_S1_S1_S1_S1_S1_fff(event_args_t *args, float *origin, float *velocity, float *ShellVelocity, float *ShellOrigin,
I don't understand review comments like this one, what do you mean, it **is hooked** on the latest commit?

2021-08-31 09:04 UTC, chinese-soup commented on BunnymodXT/modules/ClientDLL.cpp
> +			EngineDevMsg("[client dll] [WINDOWS] Found StudioCalcAttachments at %p (using pattern %s).\n", ORIG_VectorTransform, pattern->name());
So wait, you want me to go back to the commits that have mistakes that were fixed by the commit after that and fix the mistakes there or just squash it?

2021-08-31 09:13 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +			EngineDevMsg("[client dll] [WINDOWS] Found StudioCalcAttachments at %p (using pattern %s).\n", ORIG_VectorTransform, pattern->name());
I want the commits to not contain mistakes in new code. I noted some commits can be squashed into previous completely, if those commits fix mistakes then naturally you'll end up with the original commit without mistakes.

2021-08-31 09:15 UTC, YaLTeR commented on BunnymodXT/cvars.cpp
> +	CVarWrapper bxt_force_zmax("bxt_force_zmax", "0");
The point is to have good clean commits so I can review a big PR commit-by-commit without being bombarded by commented-out code, mistakes fixed in future commits and unrelated changes from merges.

2021-08-31 09:15 UTC, chinese-soup commented on BunnymodXT/modules/ClientDLL.cpp
> +			EngineDevMsg("[client dll] [WINDOWS] Found StudioCalcAttachments at %p (using pattern %s).\n", ORIG_VectorTransform, pattern->name());
alright i get it now

2021-08-31 09:39 UTC, chinese-soup commented on BunnymodXT/modules/HwDLL.cpp
> +		auto desired_viewmodel_fov = CVars::bxt_viewmodel_fov.GetFloat();
```float fovY = desired_viewmodel_fov;```

2021-08-31 09:41 UTC, chinese-soup commented on BunnymodXT/modules/HwDLL.cpp
> +		auto desired_viewmodel_fov = CVars::bxt_viewmodel_fov.GetFloat();
yea i shall just float fovY = CVars::bxt_viewmodel_fov.GetFloat();

2021-08-31 11:25 UTC, chinese-soup commented on BunnymodXT/modules/ClientDLL.cpp
> +	HwDLL::GetInstance().currentRenderFOV = pcldata->fov;
From what I understand the player would have to change the FOV on the same frame as zooming the crossbow/357/etc., but I've moved it down just to be sure, yea.

2021-09-01 05:54 UTC, YaLTeR requested changes
Also some warnings on the Windows build:
```
  HwDLL.cpp
D:\a\BunnymodXT\BunnymodXT\BunnymodXT\modules\HwDLL.cpp(4721,39): warning C4244: '=': conversion from 'double' to 'GLfloat', possible loss of data [D:\a\BunnymodXT\BunnymodXT\build\BunnymodXT.vcxproj]
  ClientDLL.cpp
D:\a\BunnymodXT\BunnymodXT\BunnymodXT\modules\ClientDLL.cpp(667,15): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data [D:\a\BunnymodXT\BunnymodXT\build\BunnymodXT.vcxproj]
D:\a\BunnymodXT\BunnymodXT\BunnymodXT\modules\ClientDLL.cpp(668,14): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data [D:\a\BunnymodXT\BunnymodXT\build\BunnymodXT.vcxproj]
```

2021-09-01 05:54 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +extern "C" void __cdecl _Z15VectorTransformPKfPA4_fPf(float *in1, float *in2, float *out)
```suggestion

extern "C" void __cdecl _Z15VectorTransformPKfPA4_fPf(float *in1, float *in2, float *out)
```

2021-09-01 05:54 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +			ORIG_StudioCalcAttachments,
```suggestion
			ORIG_EV_GetDefaultShellInfo,
			ORIG_StudioCalcAttachments,
```

2021-09-01 05:54 UTC, YaLTeR commented on BunnymodXT/stdafx.hpp
> +
Of course no ready for review PR is complete without an extra blank line
```suggestion
```

2021-09-01 08:40 UTC, hobokenn commented on BunnymodXT/modules/HwDLL.cpp
> +				EngineWarning("[client dll] Special effects of weapons will be misplaced when bxt_viewmodel_fov is used.\n");
```suggestion
				EngineWarning("[hw dll] Special effects of weapons will be misplaced when bxt_viewmodel_fov is used.\n");
```
my bad

2021-09-01 10:11 UTC, chinese-soup commented
> Also some warnings on the Windows build:

Sry didn't check that since it didn't warn in OpenAG and clang-tidy is already always full of warnings so I just don't read that at all. Fixed.

2021-09-01 10:48 UTC, YaLTeR approved these changes

2021-09-02 12:50 UTC, merged

2021-09-02 12:50 UTC, YaLTeR commented
Thanks!