Added bxt_disable_skybox
YaLTeR/BunnymodXT pull request #175
Opened 2021-08-12 01:35 UTC by SmileyAG

Recommended to use together with `gl_clear 1`

Notes: 

If someone can explain how to use **glClear** in code, then make a conversation to my code with solutions and I'll format it.
I don't know if the current changes works on Linux, please confirm it @chinese-soup
The main reason why I made this cvar is to solve #170 issue in an easy and dumb way, but if someone fixes it by modifying the wallhack or skybox-engine code, then i will close the PR (because I do not see any other use-case, which require disabling the skybox in the game)

2021-08-12 20:16 UTC, chinese-soup commented
1) Works on Linux.
2) If you wanna glClear then just add it to R_Clear like for example so:

```diff
diff --git a/BunnymodXT/modules/HwDLL.cpp b/BunnymodXT/modules/HwDLL.cpp
index cf5a7e9..50d01ac 100644
--- a/BunnymodXT/modules/HwDLL.cpp
+++ b/BunnymodXT/modules/HwDLL.cpp
@@ -4528,7 +4528,7 @@ HOOK_DEF_0(HwDLL, void, __cdecl, R_Clear)
 {
        // This is needed or everything will look washed out or with unintended
        // motion blur.
-       if (CVars::sv_cheats.GetBool() && CVars::bxt_wallhack.GetBool()) {
+       if ((CVars::sv_cheats.GetBool() && CVars::bxt_wallhack.GetBool()) || CVars::bxt_disable_skybox.GetBool()) {
                glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
                glClear(GL_COLOR_BUFFER_BIT);
        }

```

3) Which ^ reminds me - maybe this should be gated behind sv_cheats 1 like bxt_wallhack is? Let's see what others think?

2021-08-12 22:41 UTC, SmileyAG commented
>     2. If you wanna glClear then just add it to R_Clear like this for example:
> 
> 
> ```diff
> diff --git a/BunnymodXT/modules/HwDLL.cpp b/BunnymodXT/modules/HwDLL.cpp
> index cf5a7e9..50d01ac 100644
> --- a/BunnymodXT/modules/HwDLL.cpp
> +++ b/BunnymodXT/modules/HwDLL.cpp
> @@ -4528,7 +4528,7 @@ HOOK_DEF_0(HwDLL, void, __cdecl, R_Clear)
>  {
>         // This is needed or everything will look washed out or with unintended
>         // motion blur.
> -       if (CVars::sv_cheats.GetBool() && CVars::bxt_wallhack.GetBool()) {
> +       if ((CVars::sv_cheats.GetBool() && CVars::bxt_wallhack.GetBool()) || CVars::bxt_disable_skybox.GetBool()) {
>                 glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
>                 glClear(GL_COLOR_BUFFER_BIT);
>         }
> ```

Done. Thanks!

2021-08-14 21:39 UTC, hobokenn requested changes

2021-08-14 21:39 UTC, hobokenn commented on BunnymodXT/modules/HwDLL.cpp
> +		return ORIG_R_DrawSkyBox();
```suggestion
	if (CVars::sv_cheats.GetBool() && CVars::bxt_disable_skybox.GetBool())
		return;

	ORIG_R_DrawSkyBox();
```

2021-08-14 21:39 UTC, hobokenn commented on BunnymodXT/modules/HwDLL.cpp
> +	if (CVars::sv_cheats.GetBool() && CVars::bxt_wallhack.GetBool() || CVars::bxt_disable_skybox.GetBool()) {
```suggestion
	if (CVars::sv_cheats.GetBool() && (CVars::bxt_wallhack.GetBool() || CVars::bxt_disable_skybox.GetBool())) {
```

2021-08-14 21:39 UTC, hobokenn commented on BunnymodXT/patterns.hpp
> +			"55 8B EC 83 EC 1C A1 ?? ?? ?? ?? 53 56 BB 00 00 80 3F 57 C7 45 F8 00 00 00 00 85 C0"
```suggestion
			"55 8B EC 83 EC 1C A1 ?? ?? ?? ?? 53 56",
			"HL-4554",
			"83 EC 1C A1 ?? ?? ?? ?? 53 55",
			"HL-WON-1712",
			"83 EC 0C 53 55 56 57 E8 ?? ?? ?? ?? 33 FF"
```

2021-08-17 04:34 UTC, merged

2021-08-17 04:34 UTC, YaLTeR commented
Thanks