Added bxt_disable_hud
YaLTeR/BunnymodXT pull request #176
Opened 2021-08-12 05:52 UTC by SmileyAG

Pull request was marked as draft, because I need to understand how to implement disabling custom ammohistory HUD from Gunman Chronicles, let me explain how it should works:

1. Hook `8B 44 24 ?? 53 8B 5C 24 ?? 56 57 8B ?? 85 DB 8D ?? ?? 74` signature in clientside (there is no symbol link for that function)
2.1 **+0x65** from first address of function = replace byte `8C` to `8D`
2.2 **+0x6E** from first address of function = replace byte `8D` to `8C`

Showcase of custom ammohistory HUD: https://youtu.be/dg68Lh42d38?t=409 (look at the top left corner of the screen)

I would be glad if someone can help me implement this.

2021-08-12 18:27 UTC, hobokenn commented
@SmileyAG i was able to hook this function and zero it out, this is probably what you want to do it instead of byte changing, didn't test with wanted though.

2021-08-12 20:26 UTC, SmileyAG commented
> 
> 
> @SmileyAG i was able to hook this function and zero it out, this is probably what you want to do instead of byte changing, didn't test with wanted though.
> 
> ![image](https://user-images.githubusercontent.com/50155487/129258508-585a707e-4526-4cba-af7d-06f118163506.png)
> don't know how to disable this sprite or whatever it is, but everything else seems to be disabled
> [https://github.com/hobokenn/BunnymodXT/tree/disable-gunman-hud](https://github.com/hobokenn/BunnymodXT/tree/disable-gunman-hud?rgh-link-date=2021-08-12T18%3A27%3A06Z)

Thanks so much for implementation! Isn't not sprite, it was .tga files, you could mask out them by removing or rename `rewolf/gfx/vgui` folder

2021-08-17 04:39 UTC, YaLTeR requested changes
> If value == 2, its disables only HUD from GMC (useful for capturing segments)

I think it would be better to have a separate cvar for this like `bxt_disable_gmc_hud`.

2021-08-17 04:39 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +	}
that is a very roundabout way of writing `if (CVars::bxt_disable_hud.GetInt() != 1)`

2021-08-17 04:39 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +			ORIG_CWeaponStatusPanel__AddToHistory(thisptr, edx, param1, param2);
Hm, how does this work? Why would commenting out a function called `CWeaponStatusPanel::AddToHistory` disable HUD drawing? I guess it's related to why bxt-rs HUD upscale didn't work for it, because they draw HUD in a weird spot in the code?

2021-08-17 04:39 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +	}
but anyway with 2 separate cvars this would be a GetBool

2021-08-17 04:53 UTC, SmileyAG commented on BunnymodXT/modules/ClientDLL.cpp
> +	}
Well, i'm kinda low-skill in coding / reverse-engineering, so feel free to correct me, i'll take a note.

And yeah, I'll just do another cvar later for this as you said.

2021-08-18 02:41 UTC, YaLTeR approved these changes

2021-08-18 03:02 UTC, SmileyAG commented on BunnymodXT/modules/ClientDLL.cpp
> +			ORIG_CWeaponStatusPanel__AddToHistory(thisptr, edx, param1, param2);
> 
> 
> Hm, how does this work? Why would commenting out a function called `CWeaponStatusPanel::AddToHistory` disable HUD drawing? I guess it's related to why bxt-rs HUD upscale didn't work for it, because they draw HUD in a weird spot in the code?

Well, Gunman Chronicles, besides using sprites, also uses .tga files for HUDs, I don't think you hooked / modified some related function of them in bxt-rs.

Ammohistory HUD looks like really draw in a weird spot of code, cuz zero out `HUD_Redraw` and `VGUI_Label_Paint` functions doesn't rid some black semi-transparent box in left up corner of game, this is the reason why we doing zero out of history function itself to get rid that box.

2021-08-19 14:06 UTC, hobokenn commented on BunnymodXT/modules/ClientDLL.cpp
> +			ORIG_CWeaponStatusPanel__AddToHistory(thisptr, edx, param1, param2);
would it be better to disable vgui on the engine side like this? https://www.youtube.com/watch?v=6rsNZ9jH_F0

2021-08-19 16:12 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +			ORIG_CWeaponStatusPanel__AddToHistory(thisptr, edx, param1, param2);
not sure disabling vgui is better here

2021-08-19 16:21 UTC, hobokenn commented on BunnymodXT/modules/ClientDLL.cpp
> +			ORIG_CWeaponStatusPanel__AddToHistory(thisptr, edx, param1, param2);
one advantage is that it would work for other games and supersede AddToHistory and VGUI_Label_Paint

2021-08-19 16:25 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +			ORIG_CWeaponStatusPanel__AddToHistory(thisptr, edx, param1, param2);
so have bxt_disable_hud and bxt_disable_vgui?

2021-08-19 16:26 UTC, hobokenn commented on BunnymodXT/modules/ClientDLL.cpp
> +			ORIG_CWeaponStatusPanel__AddToHistory(thisptr, edx, param1, param2);
something like that, yeah

2021-08-20 02:46 UTC, YaLTeR approved these changes

2021-08-21 11:30 UTC, merged

2021-08-21 11:30 UTC, YaLTeR commented
Thanks!