Hud extensions
YaLTeR/BunnymodXT pull request #203
Opened 2021-10-03 23:34 UTC by Eddio0141

Quite a while back I crashed my game and it was to do in triangle_drawing.cpp around line 663 but I couldn't recreate the crash and couldn't think of a fix. I might have accidentally fixed it but I'm not sure.

Health and armor data is now being sent from the client and is working, but tas editor status shows you have 0 hp and armor by default until simulation updates it. I'm not sure if that's a good way to say the server doesn't know what health and armor it has at whatever framebulk selected.

2021-10-04 02:35 UTC, SmileyAG commented
You didn't changed `ry` offsets of existed HUDs and now it overlay on them:

![изображение](https://user-images.githubusercontent.com/58108407/135785041-a99da407-fae3-4873-9ec1-92e50a64c9c0.png)

Enable all HUDs: `bxt_hud_speedometer 0;bxt_hud_distance 1;bxt_hud_entity_info 1;bxt_hud_gonarch 1;bxt_hud_nihilanth 1;bxt_hud_origin 1;bxt_hud_selfgauss 1;bxt_hud_tas_editor_status 1;bxt_hud_velocity 1;bxt_hud_viewangles 1;bxt_hud_visible_landmarks 1`

2021-10-04 04:52 UTC, YaLTeR commented
Maybe we should move default TAS editor status position somewhere else so there's no overlap problem with the right side HUD stack?

2021-10-04 05:11 UTC, YaLTeR requested changes

2021-10-04 05:11 UTC, YaLTeR commented on BunnymodXT/hud_custom.cpp
> +			out << "Real Yaw: " << player_realyaw_status << '\n';
"Yaw" vs. "Real Yaw" is confusing. I suggest something like "Strafing Yaw" and "Camera Yaw"

2021-10-04 05:11 UTC, YaLTeR commented on BunnymodXT/simulation_ipc.cpp
> +		SIMULATED_FRAME = 0
Trailing commas are there for a reason—you can add or remove lines without changing the previous line, which clutters the diff and leads to conflicts. Please leave them.

2021-10-04 05:11 UTC, YaLTeR commented on BunnymodXT/triangle_drawing.cpp
> +					current_frame += input.frame_bulks[i].GetRepeats();
I believe closest frame is already computed above for use in insert_point.

2021-10-04 05:11 UTC, YaLTeR commented on BunnymodXT/triangle_drawing.cpp
> +				// TODO: fix some rare? crash that might still exist
The crash is probably that when the part has not yet been predicted, player_datas may not have current_frame.

2021-10-04 05:11 UTC, YaLTeR commented on BunnymodXT/input_editor.cpp
> +	if (player_health_datas.size() > 1) {
Why are these special-cased like this? I'd prefer that they are handled in exactly the same way as all other vectors here.

2021-10-04 05:11 UTC, YaLTeR commented on BunnymodXT/hud_custom.cpp
> +	static float player_armor_status;
Just add these into FrameBulkStatus and maybe rename it to something like TASEditorStatus

2021-10-04 05:11 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +					armor
Leave trailing comma

2021-10-04 05:11 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	// needed: m_nodeTime
Do you want to resolve this before merging? Otherwise just remove the comment, we can add the info as we need it.

2021-10-04 05:11 UTC, YaLTeR commented on BunnymodXT/triangle_drawing.cpp
> +				uint64_t current_frame = 0;
The indentation is 1 tab more than needed.

2021-10-04 08:39 UTC, Eddio0141 commented
ok this should be everything now

2021-10-04 10:54 UTC, YaLTeR commented on BunnymodXT/input_editor.cpp
> +	// only push back if the simulated frame doesn't exist
Just push zeros in simulate() along with others, so all vectors are handled in exactly the same way. This significantly reduces potential for mistakes.

2021-10-04 10:54 UTC, YaLTeR commented on BunnymodXT/simulation_ipc.cpp
> -			frame,
give comma back pls

2021-10-04 10:54 UTC, YaLTeR commented on BunnymodXT/triangle_drawing.cpp
> +			if (data_size >= closest_edge_frame) {
This should be >. `vector[vector.size()]` is accessing one value past the end.

2021-10-04 10:54 UTC, YaLTeR commented on BunnymodXT/triangle_drawing.cpp
> +			if (data_size >= closest_edge_frame) {
Also why is data_size defined above instead of right in the condition?

2021-10-04 10:54 UTC, YaLTeR commented on BunnymodXT/triangle_drawing.cpp
> +			if (input.player_health_datas.size() > closest_edge_frame) {
You won't need the separate condition once you unify the vector handling.

2021-10-05 04:41 UTC, YaLTeR commented on BunnymodXT/input_editor.cpp
> +	if (player_health_datas.size() > last_frame + 1) {
This check is no longer needed because they are handled the same way as others.

2021-10-05 04:41 UTC, YaLTeR commented on BunnymodXT/triangle_drawing.cpp
> +			if (input.player_health_datas.size() > closest_edge_frame) {
Yeah, now it's no longer needed, this can go into the condition at the top.

2021-10-05 11:20 UTC, YaLTeR approved these changes

2021-10-05 12:04 UTC, chinese-soup commented
Hello, this still cuts into bxt_hud_selfgauss by default when pointing at an entity that has a name.

Entity with targetname:
![image](https://user-images.githubusercontent.com/5108747/136018839-975517c0-c722-4682-b8a1-b3de3e70fffc.png)
Entity with no targetname (e.g. worldspawn)
![image](https://user-images.githubusercontent.com/5108747/136018850-ad076da6-51ff-41cc-8aa5-f0dcf2dbba0c.png)

2021-10-05 14:01 UTC, chinese-soup requested changes
How about something like this for the stringified sequence? (If this is what you meant, from `dlls/bigmomma.cpp:int GetNodeSequence( void )`)

2021-10-05 14:01 UTC, chinese-soup commented on BunnymodXT/modules/ServerDLL.cpp
> +bool ServerDLL::GetGonarchInfo(float &health, int& sequence, float& frame) const {
```suggestion
bool ServerDLL::GetGonarchInfo(float &health, int &sequence, float& frame, std::string& sequence_string) const {
```

2021-10-05 14:01 UTC, chinese-soup commented on BunnymodXT/modules/ServerDLL.cpp
> +
```suggestion
sequence_string = std::string(GetString(pent->v.netname));

```

2021-10-05 14:01 UTC, chinese-soup commented on BunnymodXT/modules/ServerDLL.hpp
> +	bool GetGonarchInfo(float& health, int& sequence, float& frame) const;
```suggestion
	bool GetGonarchInfo(float& health, int& sequence, float& frame, std::string& sequence_string) const;
```

2021-10-05 23:08 UTC, Eddio0141 commented
uhh how can i pull the latest commit from here so I can test it and fix something going wrong?

2021-10-06 04:30 UTC, merged

2021-10-06 04:30 UTC, YaLTeR commented
Thanks!