Added bxt_novis_serverside
YaLTeR/BunnymodXT pull request #278
Opened 2022-04-04 22:12 UTC by SmileyAG

About `kRenderFxEntInPVS` from Spirit SDK: https://github.com/LogicAndTrick/halflife-updated/blob/mods/twhl-tower-2/dlls/client.cpp#L1274

2022-04-05 12:34 UTC, YaLTeR requested changes

2022-04-05 12:34 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +			MemUtils::ReplaceBytes(reinterpret_cast<void*>(pAddToFullPack_PVS_Byte), 1, reinterpret_cast<const byte*>(CVars::bxt_novis_serverside.GetBool() ? "\xEB" : "\x74"));
This removes the check but it never adds it back when the cvar is disabled.

2022-04-05 12:34 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (CVars::bxt_novis_serverside.GetBool())
Unclear name. `bxt_novis` comes from `r_novis` or something (and it is also serverside). Maybe this can be more descriptive like `bxt_render_far_entities`?

2022-04-05 13:20 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +			MemUtils::ReplaceBytes(reinterpret_cast<void*>(pAddToFullPack_PVS_Byte), 1, reinterpret_cast<const byte*>(CVars::bxt_novis_serverside.GetBool() ? "\xEB" : "\x74"));
Oh, right. I wrote that logic being a too sleepy, and for some reason added a extra check which makes no return byte back LMAO

2022-04-05 20:05 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (pAddToFullPack_PVS_Byte)
Could you also check for the existing byte value for extra safety, like in bxt_bhopcap iirc?

2022-04-06 05:34 UTC, merged

2022-04-06 05:34 UTC, YaLTeR commented
Thanks!