Don't apply HLTV model fix if viewdemo command not found
YaLTeR/BunnymodXT pull request #307
Opened 2022-06-11 13:06 UTC by SmileyAG

https://github.com/YaLTeR/BunnymodXT/blob/0e492eed05ee48cb4d2e911380ef948cdd05b315/BunnymodXT/modules/ClientDLL.cpp#L1330

That makes prevent crashing of 1712 build when it tries to find `IsSpectateOnly`, since it's not exist in that build as `viewdemo` cmd as well.

2022-06-11 14:52 UTC, YaLTeR requested changes

2022-06-11 14:52 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +	if (pEngfuncs->pDemoAPI->IsPlayingback() && HwDLL::GetInstance().ORIG_Cmd_FindCmd("dem_forcehltv") && pEngfuncs->IsSpectateOnly())
This will do a string search on all commands every time this function runs. This has nontrivial performance overhead, better to do it some other way (perhaps searching for the command once at startup).

2022-06-12 01:34 UTC, SmileyAG commented on BunnymodXT/modules/ClientDLL.cpp
> +	if (pEngfuncs->pDemoAPI->IsPlayingback() && HwDLL::GetInstance().ORIG_Cmd_FindCmd("dem_forcehltv") && pEngfuncs->IsSpectateOnly())
I did a lot of researching and found that best place for that checks would be `HUD_Init` function, since it calls only once when ClientDLL is loaded.

I also moved `cl_righthand` check to `HUD_Init` too, since I didn't noticed that it isn't worked before :KEKW

2022-06-12 02:24 UTC, SmileyAG commented
`cl_righthand` makes no sense to move at `HUD_Frame`, since initialize in engine comes with `HUD_Init`:

![0](https://user-images.githubusercontent.com/58108407/173211649-f272119c-2319-494e-9008-607cbf7accaf.PNG)

2022-06-12 02:40 UTC, SmileyAG commented
After a dozen of force-pushing, I finally got a good working checks now, so I will not touch this PR anymore, unless there is would be some requsted review for changes.

2022-06-12 03:09 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +	if (!orig_forcehltv_found && HwDLL::GetInstance().ORIG_Cmd_FindCmd("dem_forcehltv"))
If the command is missing, this check will still run every frame I'm afraid.

2022-06-12 03:29 UTC, SmileyAG commented on BunnymodXT/modules/ClientDLL.cpp
> +	if (!orig_forcehltv_found && HwDLL::GetInstance().ORIG_Cmd_FindCmd("dem_forcehltv"))
I think check should be looks like that then:

```
if (!stop_call_forcehltv_per_frame && HwDLL::GetInstance().ORIG_Cmd_FindCmd("dem_forcehltv")) {
  orig_forcehltv_found = true;
  stop_call_forcehltv_per_frame = true;
}
else if (!stop_call_forcehltv_per_frame && !HwDLL::GetInstance().ORIG_Cmd_FindCmd("dem_forcehltv")) {
  stop_call_forcehltv_per_frame = true;
}
```

2022-06-12 03:34 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +	if (!orig_forcehltv_found && HwDLL::GetInstance().ORIG_Cmd_FindCmd("dem_forcehltv"))
Could be simpler:

```
if (check_forcehltv) {
  check_forcehltv = false;
  found = FindCmd("dem_forcehltv");
}
```

2022-06-12 14:00 UTC, merged

2022-06-12 14:00 UTC, YaLTeR commented
Thanks