Implement Discord RPC
YaLTeR/BunnymodXT pull request #319
Opened 2022-07-14 04:05 UTC by SmileyAG

# Thumbnails:

https://drive.google.com/drive/u/0/folders/1vvTY2FCAkei0PbhedUxbuvsq6cxOYl4f

# Preview:

![preview](https://user-images.githubusercontent.com/58108407/178896014-d9b894c3-9fe2-4dd1-b6af-4e6a4ac9a0fe.png)

2022-07-14 04:09 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +		constexpr const char CLIENT_ID[] = "962015108714885150";
@YaLTeR Need to create new applicaition in **Discord Developer Portal** and share his public ID.

2022-07-14 10:23 UTC, hobokenn commented on BunnymodXT/Windows/dllmain.cpp
> +	discord_integration::initialize();
any reason to do initialization in different places for windows and linux?

2022-07-14 14:48 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +	discord_integration::shutdown();
I was thinking that for BXT the Discord integration should probably never be shutdown (why restart it needlessly when restarting the engine?). Then initialization can be done from `on_frame()` on demand (i.e. if not initialized yet). This should remove the need for these new hooks.

2022-07-14 17:52 UTC, SmileyAG commented on BunnymodXT/modules/ClientDLL.cpp
> +	discord_integration::shutdown();
Done in https://github.com/YaLTeR/BunnymodXT/pull/319/commits/929849c14b1d8e16eccef5ce923b9ce23e6fe822

2022-07-17 04:31 UTC, YaLTeR requested changes
Thanks, this is really cool! I can already think of a few other states I would add to the Discord integration, for example "TASing" with some fun stats

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +				int total_time = (CustomHud::GetTime().hours * 60 * 60) + (CustomHud::GetTime().minutes * 60) + CustomHud::GetTime().seconds;
Extract `CustomHud::GetTime()` to a variable so it's only called once.

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +					if (ClientDLL::GetInstance().pEngfuncs)
Move this check into `get_map_name` and return an empty string if it fails.

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +				auto map_path = ClientDLL::GetInstance().pEngfuncs->pfnGetLevelName();
Can this return `NULL`?

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +									presence.largeImageKey = hl1_map_name_to_thumbnail.find(map_name)->second.data();
Can't you do something like `hl1_map_name_to_thumbnail[map_name].data()`? not sure

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +
```suggestion
```
and the ones below too

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +				int total_time = (CustomHud::GetTime().hours * 60 * 60) + (CustomHud::GetTime().minutes * 60) + CustomHud::GetTime().seconds;
I see there's a variable below, just move it here

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +							sprintf(buffer_details, "Map: %s | Game: %s", map_name, gameDir);
All `sprinf` calls should be `snprintf` with the correct size to avoid buffer overflows.

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +				sprintf(buffer_state, "%s | FPS Max: %g | Skill: %u", state.c_str(), CVars::fps_max.GetFloat(), CVars::skill.GetInt());
I would change "FPS Max" to just "FPS" and "Skill: N" to "Difficulty: Easy/Normal/Hard"

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +			"In menu"s,
```suggestion
			"In the menu"s,
```

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +				sprintf(buffer_state, "%s | FPS Max: %g | Skill: %u", state.c_str(), CVars::fps_max.GetFloat(), CVars::skill.GetInt());
Also instead of `%g` use `%.1f`—this should ensure single decimal digit

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +						presence.smallImageText = "BXT prevented the crash, so that run is no longer valid!";
```suggestion
						presence.smallImageText = "Invalid run (game crash prevented by BXT)";
```

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +						presence.smallImageText = "BXT timer is activated. Good luck for the run!";
```suggestion
						presence.smallImageText = "Run in progress";
```
the whole "BXT timer is activated. Good luck for the run!" is too long imo and good luck is unnecessary in the discord status

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +					presence.smallImageText = "BXT timer is disabled. Using normal time instead.";
```suggestion
					presence.smallImageText = "Not running";
```

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +					sprintf(buffer_stop, "Timer stopped at %d:%d:%d.%d", gt.hours, gt.minutes, gt.seconds, gt.milliseconds);
```suggestion
					sprintf(buffer_stop, "Timer stopped at %d:%02d:%02d.%03d", gt.hours, gt.minutes, gt.seconds, gt.milliseconds);
```
Ideally it should avoid e.g. printing the hour digit when it's 0 hours, like the BXT timer HUD itself, but it's ok

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +					presence.smallImageText = "BXT timer is stopped. Might be run finished?";
```suggestion
					presence.smallImageText = "Timer stopped";
```

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +				presence.buttonLabel[0] = "Download";
kinda weird having those two buttons but it's ok i guess?

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +	discord_integration::on_frame();
I wonder if maybe there's some engine function where you can put these callbacks so we don't depend on the client dll patterns

2022-07-17 04:31 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.hpp
> +	bool Called_TimerStop = false;
I don't see these used anywhere?

2022-07-17 04:31 UTC, YaLTeR commented on LICENSE-discord-rpc
> +Copyright 2017 Discord, Inc.
Add this into LICENSE instead of a separate file

2022-07-17 06:56 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +				int total_time = (CustomHud::GetTime().hours * 60 * 60) + (CustomHud::GetTime().minutes * 60) + CustomHud::GetTime().seconds;
Done.

2022-07-17 06:57 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +									presence.largeImageKey = hl1_map_name_to_thumbnail.find(map_name)->second.data();
> Can't you do something like `hl1_map_name_to_thumbnail[map_name].data()`? not sure

Got tried rn, seems to gives some compiler errors.

2022-07-17 06:57 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +
Done.

2022-07-17 06:58 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +							sprintf(buffer_details, "Map: %s | Game: %s", map_name, gameDir);
Like that right?

```
char buffer_details[128];

snprintf(buffer_details, sizeof(buffer_details), "Map: %s | Game: %s", map_name, gameDir);
```

2022-07-17 06:59 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +				sprintf(buffer_state, "%s | FPS Max: %g | Skill: %u", state.c_str(), CVars::fps_max.GetFloat(), CVars::skill.GetInt());
Done.

2022-07-17 06:59 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +			"In menu"s,
Done.

2022-07-17 06:59 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +						presence.smallImageText = "BXT prevented the crash, so that run is no longer valid!";
Done.

2022-07-17 06:59 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +						presence.smallImageText = "BXT timer is activated. Good luck for the run!";
Done.

2022-07-17 06:59 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +					sprintf(buffer_stop, "Timer stopped at %d:%d:%d.%d", gt.hours, gt.minutes, gt.seconds, gt.milliseconds);
Done.

2022-07-17 06:59 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +					presence.smallImageText = "BXT timer is disabled. Using normal time instead.";
Done.

2022-07-17 06:59 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +					presence.smallImageText = "BXT timer is stopped. Might be run finished?";
Done.

2022-07-17 07:01 UTC, SmileyAG commented on BunnymodXT/modules/HwDLL.hpp
> +	bool Called_TimerStop = false;
> I don't see these used anywhere?

Look at `timer_changes` function in **discord_integration.cpp** module to understand what it does.

2022-07-17 07:01 UTC, SmileyAG commented on LICENSE-discord-rpc
> +Copyright 2017 Discord, Inc.
Done.

2022-07-17 07:03 UTC, SmileyAG commented on BunnymodXT/modules/ClientDLL.cpp
> +	discord_integration::on_frame();
> I wonder if maybe there's some engine function where you can put these callbacks so we don't depend on the client dll patterns

What purpose? It only makes sense if u want to support functions for encrypted `client.dll` without adding workarounds to `hl.exe` calls

2022-07-17 07:09 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +				presence.buttonLabel[0] = "Download";
I think it works as some act of promoting to speedrunning, don't think that it useless tbh.

2022-07-17 07:13 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +					if (ClientDLL::GetInstance().pEngfuncs)
You are about `if (ClientDLL::GetInstance().pEngfuncs)`, right?

Don't think it needs move to **get_map_name**, since all of actions inside of that check is tied to `pEngfuncs` , like getting the **gamedir** at few lines below e.g.

2022-07-17 10:37 UTC, hobokenn commented on BunnymodXT/modules/ClientDLL.cpp
> +	discord_integration::on_frame();
> I wonder if maybe there's some engine function where you can put these callbacks so we don't depend on the client dll patterns

these client.dll functions are exported

2022-07-17 17:51 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +	discord_integration::on_frame();
oh

2022-07-17 17:53 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.hpp
> +	bool Called_TimerStop = false;
ah, i see

2022-07-17 17:54 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.hpp
> +	bool Called_TimerStop = false;
Maybe then just set `dirty` directly or something? Instead of having 4 extra variables

2022-07-19 02:24 UTC, SmileyAG commented
@YaLTeR Is there some more reviews or it can be prepared for merge?

2022-07-24 08:03 UTC, SmileyAG commented
Update (24.07.2022): Got made a chapter list for more HL modifications, but covers isn't done yet for them (going do it tomorrow I guess).

2022-07-26 10:08 UTC, hobokenn commented
tested on ubuntu 22.04:
1. works with native steam and flatpak discord using a socket link described [here](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)#unsandboxed-applications)
2. unfortunately does not work with both flatpak steam & discord, i assume because steam needs to run through a shell to inject bxt, e.g. openag rpc works fine if you run steam normally.

2022-07-30 04:30 UTC, YaLTeR commented
Giving this a try now with Flatpak Steam and Discord. Sorry it took so long; I don't have much time left with the 40-hour work week internship.

- Looks like this could use dropping `Difficulty: ` altogether, I guess it's clear enough if it just says Easy/Normal/Hard, and it should fit this way.

  ![image](https://user-images.githubusercontent.com/1794388/181872205-d8e5167e-9ff0-4c0d-8751-597c616eb710.png)
- Looks like the `fps_max` display does not update live, until a map change.
- Probably don't need to show FPS and difficulty when in the menu.
- I like the Barney the Movie default image lol

2022-07-30 05:56 UTC, YaLTeR commented
> I guess it's clear enough if it just says Easy/Normal/Hard

And if it's unknown just don't show that part

2022-07-30 08:49 UTC, SmileyAG commented
> Giving this a try now with Flatpak Steam and Discord. Sorry it took so long; I don't have much time left with the 40-hour work week internship.

That's fine. I still need to make about new 50+ covers for a few HL1 modifications (it's boring as fuck), so u still got a time to review code or test it again for a next 1-3 days for at least I think, I will let know u in Discord DMs when I'll fully done with covers.

2022-07-30 08:53 UTC, SmileyAG commented
>     * Looks like the `fps_max` display does not update live, until a map change. (difficulty too but I guess it doesn't change until a map change anyway?)

It's also updates state after **load** save as well, I don't see a reason to update it each game frame, cuz it will took extra perfomance I think?

2022-07-30 09:01 UTC, SmileyAG commented
>  I like the Barney the Movie default image lol

😃

In case if u want to use it for own RPC instead of making BXT logo, be free to took it:

![default](https://user-images.githubusercontent.com/58108407/181903268-e9e165f7-2ea2-4e2c-b5ba-35430a4daf77.png)

2022-07-30 14:57 UTC, YaLTeR commented
> I don't see a reason to update it in real-time, cuz it will took extra perfomance I think?

I mean just check if fps_max matches the previous value and if not update presence I guess?

2022-07-30 17:21 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.hpp
> +	bool Called_TimerStop = false;
Revisiting the last comment since now Called_Timer is also set if the fps_max changed, so it makes sense to just set dirty in discord integration?

2022-08-08 00:36 UTC, YaLTeR approved these changes

2022-08-08 00:48 UTC, merged

2022-08-08 00:48 UTC, YaLTeR commented
Thanks a lot again!