Bullet tracer implementation
YaLTeR/BunnymodXT pull request #321
Opened 2022-07-16 21:33 UTC by Eddio0141

`bxt_show_bullets` and `bxt_show_bullets_enemy` to show or hide bullet tracers.

`bxt_show_bullets_limit` and `bxt_show_bullets_enemy_limit` to limit max line counts.
If the line count exceeds the limit, it erases from the oldest lines.

`bxt_show_bullets_color` and `bxt_show_bullets_enemy_color` to set colour for each tracers with "r g b" format.

`bxt_show_bullets_clear` and `bxt_show_bullets_enemy_clear` to clear current tracers.

2022-07-16 23:07 UTC, chinese-soup commented
Change `ULONG` to `unsigned long`.

2022-07-16 23:27 UTC, Eddio0141 commented
> Get rid of __thiscall for this to build on Linksus.

When I try to do that, it crashes whenever FireBullets is called for windows
I'm not sure how to fix that

2022-07-16 23:28 UTC, chinese-soup commented
> > Get rid of __thiscall for this to build on Linksus.
> 
> When I try to do that, it crashes whenever FireBullets is called for windows I'm not sure how to fix that

All the other Windows funcs use `__fastcall`, does it not work with `__fastcall`?

2022-07-16 23:53 UTC, Eddio0141 commented
Ok yeah I changed it to __fastcall
I had to fix some arguments for the windows side too and this fixed the crashing but idk whats the argument used for

2022-07-17 01:26 UTC, chinese-soup requested changes

2022-07-17 01:26 UTC, chinese-soup commented on BunnymodXT/modules/ServerDLL.cpp
> +
my bad remove this line

2022-07-17 01:27 UTC, chinese-soup requested changes

2022-07-17 01:27 UTC, chinese-soup commented on BunnymodXT/modules/ClientDLL.cpp
> +
this time not my bad, but remove this line before yalter has a field day

2022-07-17 01:29 UTC, chinese-soup commented
Also pls retest on Windows if it still works, just in case, because I've changed the order of finding the ORIGinal function for `FireBulletsPlayer`, because it was matching something else in the Linux ServerDLL.

2022-07-17 02:40 UTC, Eddio0141 commented
![image](https://user-images.githubusercontent.com/31967258/179381619-751d9b01-711d-42bc-a384-71fc37c13fd4.png)

2022-07-17 07:06 UTC, Eddio0141 commented
Added `bxt_show_bullets_miss_alpha` and `bxt_show_bullets_enemy_miss_alpha` to control how transparent the lines get when it hits worldspawn

2022-07-17 20:05 UTC, Eddio0141 commented
Is there a good way of knowing if the entity is something like wall?
Right now im determining if the bullets fired aren't hitting anything by checking if the hit entity's class name is "worldspawn" "func_wall" or "func_wall_toggle".

2022-07-17 20:46 UTC, SmileyAG commented
> Is there a good way of knowing if the entity is something like wall?

`ent->v.solid == SOLID_BSP || ent->v.movetype == MOVETYPE_PUSHSTEP` (https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/dlls/cbase.h#L197)

2022-07-17 22:08 UTC, YaLTeR requested changes
This is very cool! Just a few comments.

2022-07-17 22:08 UTC, YaLTeR commented on BunnymodXT/cvars.cpp
> +	CVarWrapper bxt_show_bullets_miss_alpha("bxt_show_bullets_miss_alpha", "0.3");
I think these three cvars aren't really needed, just hardcode some reasonable values. (and the same for the enemy ones)

2022-07-17 22:08 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +		ServerDLL::GetInstance().ClearBulletsEnemyTrace();
This seems like it'll only run with bxt_autopause set which is not what was intended?

2022-07-17 22:08 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	ServerDLL::ClearBulletsEnemyTrace();
Are these changelevel triggers needed? I would imagine the CBuf_Execute calls should cover all changelevels?

2022-07-17 22:08 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (!igmon && (fireBullets_count || fireBulletsPlayer_count)) {
I would invert the condition so instead of
```
if (something) {
    // lots of code
}
```
it's
```
if (!something)
    return;

// lots of code
```

2022-07-17 22:08 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +const std::deque<std::array<Vector, 2>>* ServerDLL::GetBulletsEnemyTrace() const {
Why not return references instead of pointers?

2022-07-17 23:35 UTC, Eddio0141 commented
Is this good now?

2022-07-17 23:57 UTC, YaLTeR commented
ah dang it of course i messed up the formatting because the dumb web editor makes it unclear and cannot preview changes

2022-07-18 17:33 UTC, Eddio0141 commented
Ok this is everything. I've tested it on windows.
Just fixed stuff and made the clear bullets call only happen on level change.

2022-07-18 20:42 UTC, SmileyAG requested changes

2022-07-18 20:42 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.hpp
> +	HOOK_DECL(void, __cdecl, UTIL_TraceLine, const Vector* vecStart, const Vector* vecEnd, int igmon, edict_t* pentIgnore, TraceResult* ptr)
Remove those `UTIL_TraceLine` declaration hooks from **ServerDLL.hpp**, because I forgot to remove them when I did traceline hook refactoring with engine.

2022-07-19 02:24 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +  }
```suggestion
	}
```

2022-07-19 02:24 UTC, merged

2022-07-19 02:24 UTC, YaLTeR commented
Thanks! This is a great addition.