Necromancing CS1.6 support from cs branch
YaLTeR/BunnymodXT pull request #322
Opened 2022-07-20 17:31 UTC by khanghugo

From https://github.com/YaLTeR/BunnymodXT/compare/master...cs

This was a feature long time ago that enables further TAS capability in CS1.6 but long remains unsupported. I just want it back.

One thing, Windows pattern is 7 years old but I've checked the instructions for client.dll and it looks reasonable enough to work.

Here are the bytes to patch (just using cl_yawspeed as an example)
![pattern1](https://user-images.githubusercontent.com/29143195/180044038-9ac638ae-801b-4db3-aff0-f91f98dea062.png)
![pattern2](https://user-images.githubusercontent.com/29143195/180044070-5babef97-1db8-46be-9a87-9d83d9e9bc4d.png)

And this is the result
![pattern_patched](https://user-images.githubusercontent.com/29143195/180044137-1afef15f-56e6-4e7a-9fcf-f77d4e19eb07.png)
The patch will push cl_yawspeed and cl_pitchspeed value onto top stack regardless of any branching involving comparison between itself and the two other limit values. 

I then TAS it a bit and it works. The prediction closely matches the simulator, or it just is. Before, the yaw lock would not only prevent the script from strafing closer but also all the new fancy camera smoothing stuffs.

For attributions, I have never written a line of code in my entire life so most of things here are simply mirroring already existing code and mainly the one you had initially in the cs branch.

2022-07-30 03:18 UTC, YaLTeR requested changes
Instead of just updating the HLStrafe submodule commit to your fork, you should PR the change into HLStrafe, and when that's merged, subsequently update the submodule to point at the commit in the main HLStrafe repo.

2022-07-30 03:18 UTC, YaLTeR commented on BunnymodXT/patterns.hpp
> +			);
```suggestion
		);
```

2022-07-30 03:18 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +			MemUtils::ReplaceBytes(reinterpret_cast<void*>(pCS_AngleSpeedCap + 5), 1, reinterpret_cast<const byte*>("\x7B"));
Since this and SetSpeedScaling are run every frame, and replacing bytes involves potentially performance-sensitive operations like changing the memory protection flags, before calling `ReplaceBytes` you should check if the bytes need to be replaced. I believe the `bxt_bhopcap` code does that as an example.

2022-08-01 14:19 UTC, khanghugo commented
Thanks for the feedback. I didn't really intend to have these commits flooding over here. Let me see what I can do to clean them up.

2022-08-08 00:50 UTC, YaLTeR approved these changes

2022-08-09 08:42 UTC, SmileyAG requested changes

2022-08-09 08:42 UTC, SmileyAG commented on BunnymodXT/modules/HwDLL.cpp
> +		vars.Maxspeed = 250.0f; // sv_maxspeed does not override the speed unless below 300
Can you remove that maxspeed hack and go check #325 request?

2022-08-09 13:56 UTC, khanghugo commented on BunnymodXT/modules/HwDLL.cpp
> +		vars.Maxspeed = 250.0f; // sv_maxspeed does not override the speed unless below 300
Thanks for the help. I got it working perfectly with that.

2022-08-10 07:48 UTC, SmileyAG requested changes

2022-08-10 07:48 UTC, SmileyAG commented on BunnymodXT/hud_custom.cpp
> +			GetPosition(CVars::bxt_hud_stamina_offset, CVars::bxt_hud_stamina_anchor, &x, &y, -200, (si.iCharHeight * 16) + 4);
Need to fix offset here, since that overlaps entity info HUD: 
![изображение](https://user-images.githubusercontent.com/58108407/183844814-8804ff90-1224-49d1-b19b-6a93960b2e88.png)

2022-08-10 22:19 UTC, khanghugo commented on BunnymodXT/hud_custom.cpp
> +			GetPosition(CVars::bxt_hud_stamina_offset, CVars::bxt_hud_stamina_anchor, &x, &y, -200, (si.iCharHeight * 16) + 4);
This is at relative offset 29, right above self gauss.
![image](https://user-images.githubusercontent.com/29143195/184030457-d9050839-c904-40af-ba48-327e80eddfa7.png)

2022-08-10 22:57 UTC, khanghugo commented on BunnymodXT/hud_custom.cpp
> +			GetPosition(CVars::bxt_hud_stamina_offset, CVars::bxt_hud_stamina_anchor, &x, &y, -200, (si.iCharHeight * 16) + 4);
![image](https://user-images.githubusercontent.com/29143195/184037191-43184070-bdd4-408d-b88b-c6e98f75cc91.png)
This is another one in the middle, barely occupied by visible landmark hud. I think it should be okay there.

2022-08-18 16:29 UTC, khanghugo commented
At this stage, it is all there is. I have yet tested on Windows so I am not really sure how it would be. For further testing, I can make a small TAS for verification.

2022-08-18 16:38 UTC, khanghugo commented
At this stage, it seems pretty good. Not sure how well it would work on Windows but all the stuffs are there.

2022-08-18 18:03 UTC, khanghugo commented
Here is a small TAS that can be used to verified on Windows. Made with the commit.

https://youtu.be/vh2AdTZyWoQ

2022-08-18 18:09 UTC, khanghugo commented
Beside that, lots of things are still borked. Eg: you cannot record demo or use other things like hud_useable. It needs some more work.

2022-08-23 15:07 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +	if (cl.DoesGameDirMatch("cstrike")) {
Please cache this with a `static bool is_cstrike = cl.DoesGameDirMatch("cstrike");` so that we don't have a string comparison every frame. Also I guess when the maxspeed PR is merged (pending on a similar change) this should be rebased on top of that.

2022-08-24 04:57 UTC, YaLTeR commented
You should be able to rebase on top of master now to get Smiley's client maxspeed thing.

2022-08-24 12:45 UTC, khanghugo commented
Yep, rebase is here. If there is anything else, I can fix.

2022-08-25 02:42 UTC, merged

2022-08-25 02:42 UTC, YaLTeR commented
Thanks! Finally, the CS 1.6 support is back!