Various changes
YaLTeR/BunnymodXT pull request #327
Opened 2022-08-25 02:56 UTC by SmileyAG

- Custom support of `bxt_render_far_entities` for CSCZDS game

- Hooked engine function to see how much there is active players on server, and `if (active_players != 1)`, disallow to use cvars that can may have a advantage in multiplayer.

- Added more TAS logging patterns for games like Counter-Strike 1.6 or Team Fortress Classic, fixed offsets for `bxt_hud_useables` e.g.

- `_bxt_remove_fps_limit_conditions` in old WON allows to cap/uncap FPS upper than 100
- In Steampipe it's removes 20 FPS cap if `maxplayers > 1` (no worries, I added `sv_cheats 1` condition, so it would work if cheats on server enabled)

2022-08-25 03:07 UTC, YaLTeR requested changes

2022-08-25 03:07 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +			if (cstrike_addtofullpack_pvs_found)
Instead of setting this variable based on the pattern, I'd rather it be set based on whether the original byte was 0x74 or 0x75.

2022-08-25 03:07 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.hpp
> -	bool Called_InvalidRun = false;
This variable is unused?

2022-08-25 03:07 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +		ent->v.flags |= FL_IMMUNE_LAVA; // Because the PVS check in AddToFullPack points to '524288' flags bit
This belongs to the previous commit.

2022-08-25 03:07 UTC, YaLTeR commented on BunnymodXT/patterns.hpp
> +			"8B 44 24 ?? 50 55 FF 15 ?? ?? ?? ?? 83 C4 08 85 C0 ??"
Trailing ?? does nothing

2022-08-25 03:07 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +			if (won_host_filtertime_fps_cap_found)
Same as the other one, I'd rather this variable be set based on the original byte, not based on the pattern.

2022-08-25 03:07 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +	if (((CountPlayers() == 1) || CVars::sv_cheats.GetBool()) && CVars::bxt_fade_remove.GetBool())
I don't think we should restrict anything based on the player count. BXT does not support multiplayer, let's not pretend that it does by adding conditions to a few places. If someone uses it to cheat in multiplayer I'm not sure it's our problem to deal with that, and regardless surely there are plenty of free hacks available to choose from.

2022-08-25 03:07 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	static bool is_czeror = ClientDLL::GetInstance().DoesGameSubDirMatch("czeror");
Change belongs to previous commit, also why check for substring?

2022-08-25 03:07 UTC, YaLTeR commented on BunnymodXT/cvars.cpp
> +	CVarWrapper _bxt_remove_fps_limit_conditions("_bxt_remove_fps_limit_conditions", "0");
bxt_remove_won_fps_limit

2022-08-25 03:23 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	static bool is_czeror = ClientDLL::GetInstance().DoesGameSubDirMatch("czeror");
> Change belongs to previous commit, also why check for substring?

But what if we going to make some modifications like `czeror_cutsceneless` or either shit? I'm does it with the views on the future.

2022-08-25 03:26 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.hpp
> -	bool Called_InvalidRun = false;
Yes.

2022-08-25 03:34 UTC, SmileyAG commented on BunnymodXT/modules/HwDLL.cpp
> +	if (((CountPlayers() == 1) || CVars::sv_cheats.GetBool()) && CVars::bxt_fade_remove.GetBool())
Yeah I know that features in BXT if developing with goal to use it in local server sessions and no more, and trash cheaters would prefer some evil free hacks, but I'm still trying to minimize risks of get advantage with some cvars if someone would to use BXT for that purposes.

2022-08-25 03:38 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +	if (((CountPlayers() == 1) || CVars::sv_cheats.GetBool()) && CVars::bxt_fade_remove.GetBool())
Well I still don't think I want this in BXT. Honestly even the existing simple sv_cheats 1 check for some cvars (bxt_ch_set_health) has been fairly annoying to me during TASing and other usage.

2022-08-25 03:40 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +			if (cstrike_addtofullpack_pvs_found)
Like that, right?

```
	static bool is_0x75 = false;

	if (pAddToFullPack_PVS_Byte)
	{
		if (CVars::bxt_render_far_entities.GetBool())
		{
			if (*reinterpret_cast<byte*>(pAddToFullPack_PVS_Byte) == 0x75)
				is_0x75 = true;
		
			if ((*reinterpret_cast<byte*>(pAddToFullPack_PVS_Byte) == 0x74) || (*reinterpret_cast<byte*>(pAddToFullPack_PVS_Byte) == 0x75))
				MemUtils::ReplaceBytes(reinterpret_cast<void*>(pAddToFullPack_PVS_Byte), 1, reinterpret_cast<const byte*>("\xEB"));
		}
		else if (*reinterpret_cast<byte*>(pAddToFullPack_PVS_Byte) == 0xEB)
		{
			if (is_0x75)
				MemUtils::ReplaceBytes(reinterpret_cast<void*>(pAddToFullPack_PVS_Byte), 1, reinterpret_cast<const byte*>("\x75"));
			else
				MemUtils::ReplaceBytes(reinterpret_cast<void*>(pAddToFullPack_PVS_Byte), 1, reinterpret_cast<const byte*>("\x74"));
		}
	}
```

2022-08-25 03:41 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +			if (cstrike_addtofullpack_pvs_found)
That should work yeah

2022-08-26 03:09 UTC, YaLTeR requested changes
Please remove the `CountPlayers()` logic. Otherwise looks good to go.

2022-08-26 03:51 UTC, YaLTeR approved these changes

2022-08-26 03:52 UTC, merged

2022-08-26 03:52 UTC, YaLTeR commented
Thanks!