Fixed crash in GMC, disappear of viewmodel in firstperson HLTV, added engine build number to RPC print
YaLTeR/BunnymodXT pull request #330
Opened 2022-09-10 12:25 UTC by SmileyAG

2022-09-10 21:58 UTC, YaLTeR requested changes
To be honest, it'd be better if the unrelated changes came in separate PRs, so that the auto-generated release notes work...

2022-09-10 21:58 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +	if (!ppmove && !pEngfuncs && !orig_forcehltv_found)
Shouldn't this be `||` and check for `offIUser1 != 0`?

2022-09-10 21:58 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +						presence.smallImageText = "Demo playback";
"Watching a demo"

2022-09-10 21:58 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +						presence.smallImageText = "Demo playback";
"Watching a demo"

2022-09-10 21:58 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +	if (!ppmove || !pEngfuncs || !orig_forcehltv_found)
Can you squash this change into the relevant commit?

2022-09-10 21:58 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +								snprintf(buffer_details, sizeof(buffer_details), "Map: %s | Game: %s | Build: %i", map_name, gameDir, hw.ORIG_build_number());
Does this fit into the window though?

2022-09-10 21:58 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.hpp
> +	bool DoesGameDirMatch(const char *game, bool substr);
I would prefer if these two functions remained two functions, an extra bool parameter is confusing. Put the new logic in `DoesGameDirMatch` into a function called `GetGameDir()` or something, this way these two can be simple one liners.

2022-09-13 03:59 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +								snprintf(buffer_details, sizeof(buffer_details), "Map: %s | Game: %s | Build: %i", map_name, gameDir, hw.ORIG_build_number());
Yes.

2022-09-13 04:00 UTC, SmileyAG commented on BunnymodXT/modules/ClientDLL.hpp
> +	bool DoesGameDirMatch(const char *game, bool substr);
I don't like to have two functions cuz it confuses all time how it name called, like `DoesGameSubDirMatch` or `DoesGameDirSubMatch`.

IMO having such a boolean parameter is more convenient for me.

2022-09-13 04:02 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.hpp
> +	bool DoesGameDirMatch(const char *game, bool substr);
DoesGameDirMatch(true) or (false) doesn't tell me anything. How about DoesGameDirContain?

2022-09-13 04:03 UTC, SmileyAG commented
@YaLTeR I finished thumbnails for all other HL1 mods from **discord_integration.hpp** file, download it: https://drive.google.com/drive/u/0/folders/1_QQdazZGDh83K_frWMHxgiD_zt4dyTj6

2022-09-13 04:08 UTC, SmileyAG commented on BunnymodXT/modules/ClientDLL.hpp
> +	bool DoesGameDirMatch(const char *game, bool substr);
> DoesGameDirMatch(true) or (false) doesn't tell me anything. How about DoesGameDirContain?

You mean about still make a second function for finding gamedir or rename `DoesGameDirMatch`?

2022-09-13 04:14 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.hpp
> +	bool DoesGameDirMatch(const char *game, bool substr);
To have DoesGameDirMatch and DoesGameDirContain, two functions instead of the bool parameter.

2022-09-24 17:11 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +	}
Could you extract this into a separate function? This way both `DoesGameDirMatch` and `DoesGameDirContain` become very simple.

2022-09-26 02:28 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +							cl.FileBase(gameDir, gd);
Why did you remove the NULL check?

2022-09-28 04:47 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +						if (gameDir[0] && map_name[0])
```suggestion
						if (gameDir && gameDir[0] && map_name[0])
```

2022-09-28 18:24 UTC, merged

2022-09-28 18:24 UTC, YaLTeR commented
Thanks