Added experimental support for Cry of Fear
YaLTeR/BunnymodXT pull request #333
Opened 2022-09-18 14:57 UTC by SmileyAG

2022-10-01 03:40 UTC, YaLTeR requested changes

2022-10-01 03:40 UTC, YaLTeR commented on BunnymodXT/cvars.cpp
> +	CVarWrapper bxt_cof_enable_ducktap("bxt_cof_enable_ducktap", "0");
Why is this bxt_cof but the other cvar is bxt_..._in_cof?

2022-10-01 03:40 UTC, YaLTeR commented on BunnymodXT/hud_custom.cpp
> +		ClientDLL::GetInstance().pEngfuncs->GetViewAngles(player.viewangles);
Doesn't this change replace an engine dependency with a client dependency? We don't want that because there's much more variety in clients than in the engine.

2022-10-01 03:40 UTC, YaLTeR commented on BunnymodXT/hud_custom.cpp
> +				out << *m_fStamina;
This should not be here, it should be wherever `player.stamina` is set.

2022-10-01 03:40 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +	if (ORIG_PM_Jump && !HwDLL::GetInstance().is_cof)
Why?

2022-10-01 03:40 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +		hw.ORIG_Cmd_AddCommand("noclip", hw.ORIG_Host_Noclip_f);
Why is this in `ClientDLL::HUD_Init` and not in `HwDLL::RegisterCVarsAndCommandsIfNeeded`?

2022-10-01 03:40 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (ORIG_PM_Jump && !HwDLL::GetInstance().is_cof) {
Why?

2022-10-01 03:40 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (pCS_Stamina_Value || HwDLL::GetInstance().is_cof)
Why?

2022-10-01 03:40 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.hpp
> +	ServerDLL() : IHookableDirFilter({ L"dlls", L"cl_dlls"}) {};
Please add a CoF comment here too.

2022-10-01 09:42 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (pCS_Stamina_Value || HwDLL::GetInstance().is_cof)
For register cvar to disabling stamina limit in CoF, why it surprises you?

2022-10-01 09:48 UTC, SmileyAG commented on BunnymodXT/cvars.cpp
> +	CVarWrapper bxt_cof_enable_ducktap("bxt_cof_enable_ducktap", "0");
I'll rename `bxt_disable_save_lock_in_cof` to `bxt_cof_disable_save_lock`, thanks for point.

2022-10-01 09:57 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (ORIG_PM_Jump && !HwDLL::GetInstance().is_cof) {
`bxt_autojump` doesn't take stamina in that game after you made 1st jump in bhop sequence, while `+bxt_tas_autojump` and normal jumps does, so I think it illegal one cuz probably there is some button check in server that prevents to take stamina or smth like that, not inspected much for that question.

Hoboken suggested before to take off stamina in `bxt_autojump` code (since we already know where that memory value is placed), but that idea seems to me scuffed tbh, I rather ask runners use `+bxt_tas_autojump` and that's all.

2022-10-01 09:59 UTC, SmileyAG commented on BunnymodXT/modules/ClientDLL.cpp
> +	if (ORIG_PM_Jump && !HwDLL::GetInstance().is_cof)
https://github.com/YaLTeR/BunnymodXT/pull/333#discussion_r985079875

2022-10-01 23:06 UTC, hobokenn commented on BunnymodXT/hud_custom.cpp
> +		ClientDLL::GetInstance().pEngfuncs->GetViewAngles(player.viewangles);
since https://github.com/YaLTeR/BunnymodXT/commit/8917622040397e3eece04b6cbfd4dbe88fbc6cc9 it's an engine dependency, i tried to explain it a bit in my commit https://github.com/SmileyAG/BunnymodXT/pull/9/commits/7e7b42cea3b2104a33cab59804b0f94ad91eb761, but smiley misunderstood me and squashed my pr

2022-10-01 23:48 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (ORIG_PM_Jump && !HwDLL::GetInstance().is_cof) {
Ic

I think ideally +bxt_tas_autojump should start handling all cases it currently doesn't handle (see the OpenAG autojump) and then we can remove bxt_autojump altogether

2022-10-08 06:09 UTC, SmileyAG commented on BunnymodXT/hud_custom.cpp
> +				out << *m_fStamina;
If I'm moving it to `SetStamina` custom function (that calls at end of **Cbuf_Execute**) it would cause a game crash state-like.

2022-10-08 06:09 UTC, SmileyAG commented on BunnymodXT/modules/ClientDLL.cpp
> +		hw.ORIG_Cmd_AddCommand("noclip", hw.ORIG_Host_Noclip_f);
If I do in `HwDLL::RegisterCVarsAndCommandsIfNeeded` it outputs **Cmd_AddCommand after host_initialized** error

2022-10-08 17:30 UTC, YaLTeR commented on BunnymodXT/modules/ClientDLL.cpp
> +		hw.ORIG_Cmd_AddCommand("noclip", hw.ORIG_Host_Noclip_f);
What do you mean, we add a ton of commands there just fine?

2022-10-08 17:31 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (ORIG_PM_Jump && !HwDLL::GetInstance().is_cof) {
Could you add a comment to both here and the other place that bxt_autojump is disabled in CoF because it's extra unlegit?

2022-10-08 17:31 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (pCS_Stamina_Value || HwDLL::GetInstance().is_cof)
I didn't know that CoF had stamina.

2022-10-08 17:35 UTC, YaLTeR commented on BunnymodXT/hud_custom.cpp
> +				out << *m_fStamina;
What is `SetStamina`? I'm talking about `TryGettingAccurateInfo` where `player.stamina` is set.

2022-10-10 00:57 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +		ServerDLL::GetInstance().pEngfuncs->pfnAddServerCommand("notarget", ORIG_Host_Notarget_f);
No, if it is in `HwDLL`, it should use an engine command-adding function... The server isn't even loaded at this point

2022-10-10 01:22 UTC, SmileyAG commented on BunnymodXT/modules/HwDLL.cpp
> +		ServerDLL::GetInstance().pEngfuncs->pfnAddServerCommand("notarget", ORIG_Host_Notarget_f);
1) `pfnAddServerCommand` is not a server function, it's `Cmd_AddGameCommand` in engine.
2) That **pEngfuncs** table got hooked in engine too, find `auto fLoadThisDll = FindAsync(` line in **HwDLL.cpp**

TLDR; not need to worries at all.

2022-10-10 01:29 UTC, SmileyAG commented
@YaLTeR I think I'm done with BXT supporting to CoF for now, we got everything that needs for RTA runs or segmenting, so free to merge or review.

2022-10-10 02:51 UTC, merged

2022-10-10 02:51 UTC, YaLTeR commented
Thanks!