Added bxt_stucksave, second viewangles mode for take punches into angle account
YaLTeR/BunnymodXT pull request #335
Opened 2022-09-23 16:49 UTC by SmileyAG

@jorikgrozniy asked me to implement those features, so I did!

2022-09-24 01:45 UTC, YaLTeR requested changes

2022-09-24 01:45 UTC, YaLTeR commented on BunnymodXT/cvars.cpp
> +	CVarWrapper bxt_fire_on_mm("bxt_fire_on_mm", "0");
Unrelated change, and back when you added it we specifically decided the other way

2022-09-24 01:45 UTC, YaLTeR commented on BunnymodXT/hud_custom.cpp
> +			if (CVars::bxt_hud_viewangles.GetInt() == 2)
Could you add some indication when you have `bxt_hud_viewangles 2` so it looks different? Otherwise someone's gonna forget or leave it on by accident and then waste time trying to understand why their HUD is showing incorrect values.

2022-09-24 01:45 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (CVars::bxt_stucksave.GetBool() && !CVars::bxt_stucksave_command.IsEmpty() && ORIG_PM_CheckStuck())
Why is a separate `bxt_stucksave` needed? Just leave the empty check

2022-09-24 07:13 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +		ss << CVars::bxt_stucksave_command.GetString().c_str() << "\n";
Is it better rename to `bxt_fire_on_stuck` or smth like that?

2022-09-24 07:14 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (CVars::bxt_stucksave.GetBool() && !CVars::bxt_stucksave_command.IsEmpty() && ORIG_PM_CheckStuck())
Because otherwise it would spamming commands each frame when you got stucked, so I could disable it with like:

`bxt_stucksave_command "s4v3;bxt_stucksave 0"`

2022-09-24 07:38 UTC, SmileyAG commented on BunnymodXT/hud_custom.cpp
> +			if (CVars::bxt_hud_viewangles.GetInt() == 2)
What indication you want like? Change color? Some tag like `Pitch (second mode):`?

2022-09-24 16:50 UTC, YaLTeR commented on BunnymodXT/hud_custom.cpp
> +			if (CVars::bxt_hud_viewangles.GetInt() == 2)
What effects does cl.last_viewangles include compared to player.viewangles?

2022-09-24 16:54 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (CVars::bxt_stucksave.GetBool() && !CVars::bxt_stucksave_command.IsEmpty() && ORIG_PM_CheckStuck())
Maybe instead it should only run the command when the player was not stuck last frame? Then you don't need to disable and enable it manually.

2022-09-24 17:03 UTC, SmileyAG commented on BunnymodXT/hud_custom.cpp
> +			if (CVars::bxt_hud_viewangles.GetInt() == 2)
Client and server punchangles: 
![0](https://user-images.githubusercontent.com/58108407/192110128-fae1ea58-8739-4c16-b844-70898c096288.PNG)

2022-09-24 17:04 UTC, YaLTeR commented on BunnymodXT/hud_custom.cpp
> +			if (CVars::bxt_hud_viewangles.GetInt() == 2)
What about stuff like viewbobbing?

2022-09-24 17:13 UTC, YaLTeR commented on BunnymodXT/hud_custom.cpp
> +			if (CVars::bxt_hud_viewangles.GetInt() == 2)
If it's just punchangle then smth like Angles (incl. punch)

2022-09-26 02:30 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	not_stuck_prev_frame = stuck_cur_frame ? false : true;
```suggestion
	not_stuck_prev_frame = !stuck_cur_frame;
```

Would've saved some trouble if you made it `stuck_prev_frame` rather than `not_stuck_prev_frame`

2022-09-28 04:47 UTC, merged

2022-09-28 04:47 UTC, YaLTeR commented
Thanks