Updated README, GitHub Actions and Discord RPC for a bit
YaLTeR/BunnymodXT pull request #376
Opened 2022-12-02 18:55 UTC by SmileyAG

2022-12-05 21:35 UTC, YaLTeR requested changes
For the CI, you can also replace the Rust actions like this:
```
      - name: Install Rust
        run: |
          rustup toolchain install stable --profile minimal
          rustup override set stable
          rustup target add i686-unknown-linux-gnu
```

2022-12-05 21:35 UTC, YaLTeR commented on README.md
> +- Visual Studio 2017, 2019 or 2022
```suggestion
- Visual Studio 2019 or 2022
```
The CI builds on 2019 so we can't promise it builds on 2017.

2022-12-05 21:35 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +						if (gameDir && gameDir[0] && map_name[0] && hw.ORIG_build_number)
Why? Could you please write explanations for these types of changes?

2022-12-08 18:00 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +						if (gameDir && gameDir[0] && map_name[0] && hw.ORIG_build_number)
That's already described in name of commit: `Don't update RPC if 'build_number' function not found`

Because I don't want to update RPC if pattern for output number of engine build is missed.

2022-12-08 18:08 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +						if (gameDir && gameDir[0] && map_name[0] && hw.ORIG_build_number)
Yes, I do read commit messages. I don't understand why you don't want to update in this case. There's more info there than just the build number.

2022-12-08 18:28 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +						if (gameDir && gameDir[0] && map_name[0] && hw.ORIG_build_number)
> Yes, I do read commit messages. I don't understand why you don't want to update in this case. There's more info there than just the build number.

For all of that more information checks is already here, like `cl.pEngfuncs` and `gamedir[0] && map_name[0]`

The only thing was missed is checking for found pattern of `build_number`, because I want to know some of that specific info like.

2022-12-08 18:31 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +						if (gameDir && gameDir[0] && map_name[0] && hw.ORIG_build_number)
Yes, so why disable it altogether if there's plenty of info we can show without build_number?

2022-12-08 18:41 UTC, SmileyAG commented on BunnymodXT/discord_integration.cpp
> +						if (gameDir && gameDir[0] && map_name[0] && hw.ORIG_build_number)
> Yes, so why disable it altogether if there's plenty of info we can show without build_number?

I rather preferring to have that check at that line, since if that not success to update RPC, then user would told version of engine that is unsupported, so we can add proper support to it later.

2022-12-08 18:45 UTC, YaLTeR commented on BunnymodXT/discord_integration.cpp
> +						if (gameDir && gameDir[0] && map_name[0] && hw.ORIG_build_number)
Huh, why? What does showing map and game in discord rpc have to do with indicating to the user they are running an "unsupported build", whatever that means (I have no idea what you mean by this)?

2022-12-30 23:37 UTC, merged

2022-12-30 23:37 UTC, YaLTeR commented
Thanks!