Refactor of cvar defining
YaLTeR/BunnymodXT pull request #377
Opened 2022-12-02 19:02 UTC by SmileyAG

2022-12-05 21:37 UTC, YaLTeR requested changes

2022-12-05 21:37 UTC, YaLTeR commented on BunnymodXT/cvars.cpp
> -
unrelated change

2022-12-05 21:37 UTC, YaLTeR commented on BunnymodXT/cvars.hpp
> +#define ADD_TO_FIND_LIST(name) &name,
I'd like these "argument" macros to be defined right before they are used for clarity.

2022-12-08 18:10 UTC, SmileyAG commented on BunnymodXT/cvars.cpp
> -
I don't think so. It looks more clean when a few `#include` goes in order without a some empty line.

2022-12-08 18:18 UTC, YaLTeR commented on BunnymodXT/cvars.cpp
> -
1. stdafx is special because it is a precompiled header. It must always be the first include and it must be without any path even though it's not literally in the same folder. It's separated by a blank line to indicate this special nature.
2. The PR is about reworking cvar definition and the commit is called "Rework of cvar defining", nowhere does it mention include aesthetics.

2022-12-30 23:40 UTC, merged

2022-12-30 23:40 UTC, YaLTeR commented
Thanks!