Add target_yaw look_at and goodies
YaLTeR/BunnymodXT pull request #382
Opened 2022-12-17 21:29 UTC by khanghugo

2022-12-31 00:45 UTC, YaLTeR requested changes

2022-12-31 00:45 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +		} else if (!strcmp(what, "velocity")) {
Is this needed?

2022-12-31 00:45 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +				hw.tas_editor_set_target_yaw_look_at = true;
Shouldn't this set entity to 0?

2022-12-31 20:49 UTC, khanghugo commented on BunnymodXT/modules/HwDLL.cpp
> +		} else if (!strcmp(what, "velocity")) {
I think the cvar is needed so there would be no need to reload the script. Is target_yaw velocity needed? No. I just put it there because things come in three.

2023-01-06 23:47 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +				}
Put this unconditionally above the if. This way you avoid bugs, like the one already present in this code where you don't set to 0 when entity is > num edicts

2023-01-07 00:34 UTC, YaLTeR requested changes

2023-01-07 00:34 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +	USAGE("Usage: bxt_tas_editor_set_target_yaw_type <type>\n Set type of target_yaw for a point in the camera editor. Valid types (currently supported) are velocity_lock, look_at, and velocity.\n");
```suggestion
	USAGE("Usage: bxt_tas_editor_set_target_yaw_type <type>\n Set type of target_yaw for a point in the camera editor. Valid types (currently supported) are velocity_lock and look_at [entity <index>] [<x> <y> <z>].\n");
```

2023-01-07 00:34 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +				if (scan_entity == 4) {
Set the coordinates to 0 unconditionally before this if.

2023-01-07 00:34 UTC, YaLTeR commented on BunnymodXT/triangle_drawing.cpp
> +						case HLTAS::ConstraintsType::LOOK_AT:
Color it something different I think

2023-01-07 01:21 UTC, khanghugo commented on BunnymodXT/modules/HwDLL.cpp
> +				if (scan_entity == 4) {
Is it too much for me to believe that C has sane default?

2023-01-08 17:22 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +				if (scan_entity == 4) {
I mean float x = 0, y = 0, z = 0;

2023-01-08 18:06 UTC, merged

2023-01-08 18:07 UTC, YaLTeR commented
Thanks!