Add more bxt_ch_get_ commands to dump player info
YaLTeR/BunnymodXT pull request #415
Opened 2023-02-06 07:28 UTC by SmileyAG

2023-02-17 18:32 UTC, YaLTeR requested changes

2023-02-17 18:32 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +			out << "FL_ONTRAIN";
```suggestion
			out << "FL_ONTRAIN; ";
```
For consistency.

2023-02-17 18:32 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +
If the entity was not found it should print an error.

2023-02-17 18:32 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +			if (e != num)
Why does this need to be a loop? Just check if `num < numEdicts` and that it's a valid ent?

2023-02-17 18:32 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +			out << "; xyz: " << origin.x << " " << origin.y << " " << origin.z;
```suggestion
			out << "; position: " << origin.x << " " << origin.y << " " << origin.z;
```

2023-02-17 18:32 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +
Please extract this stuff into a separate helper function and call it from both handlers.

2023-02-17 18:32 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
>  	NO_USAGE();
With two commands with arguments this now needs a usage help string.

2023-02-17 18:32 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +			}
This is quite cursed. Honestly I'm having second thoughts on whether this two-argument variant is even needed in the first place. I'd rather just remove it

2023-02-17 18:32 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +			if (strstr(classname, name) == 0)
Could you add a second check here for targetname, if it exists? So both classname and targetname strstr will always result in printing, I think that would make sense

2023-02-17 18:32 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +	wrapper::Add<Cmd_BXT_Get_ServerTime, Handler<>>("bxt_get_servertime");
```suggestion
	wrapper::Add<Cmd_BXT_Get_Server_Time, Handler<>>("bxt_get_server_time");
```

2023-02-17 18:32 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +		case MOVETYPE_FLYMISSILE:       return "Fly-missle";
```suggestion
		case MOVETYPE_FLYMISSILE:       return "Fly-missile";
```

2023-02-17 18:32 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +		case MOVETYPE_BOUNCEMISSILE:    return "Bounce-missle";
```suggestion
		case MOVETYPE_BOUNCEMISSILE:    return "Bounce-missile";
```

2023-02-17 18:44 UTC, SmileyAG commented on BunnymodXT/modules/HwDLL.cpp
> +			out << "; xyz: " << origin.x << " " << origin.y << " " << origin.z;
Don't want to make output longer to not cause issues with printing more symbols at once, let's keep it as `xyz:` instead

2023-02-24 18:42 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +	"bxt_print_entities <target> targetname\n"
This is really not a good UI. I think we should just leave a no-argument (prints all entities) and the single-argument (prints entities matching classname or targetname) cases.

2023-03-03 17:48 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +void HwDLL::PrintEntities(std::ostringstream &out, int e, const edict_t* ent)
```suggestion
void HwDLL::PrintEntity(std::ostringstream &out, int index)
```
It can get edict itself, especially since it already gets classname and whatnot.

2023-03-05 03:12 UTC, SmileyAG commented on BunnymodXT/modules/HwDLL.cpp
> +struct HwDLL::Cmd_BXT_Print_Entities_Help
Sure.

2023-03-05 03:24 UTC, SmileyAG commented on BunnymodXT/modules/HwDLL.cpp
> +struct HwDLL::Cmd_BXT_Print_Entities_By_Index
- If printed message is too long (e.g.: output from `bxt_print_entities`) then it will not be able to be fully receive and as a result, half of the text will not be printed, so that we can split it with `bxt_print_entities_by_index`

- Example I can get index of needed entity under crosshair from `bxt_hud_entity_info`, and then I use it for `bxt_print_entities_by_index` to print needed data about entity and use for further research

2023-03-05 04:00 UTC, merged

2023-03-05 04:00 UTC, YaLTeR commented
Thanks!