Added 'bxt_disable_v_sync' to disable V-Sync in pre-Steampipe builds
YaLTeR/BunnymodXT pull request #424
Opened 2023-02-17 08:24 UTC by SmileyAG

2023-02-17 18:56 UTC, YaLTeR requested changes
Does this also work on Steam builds?

2023-02-17 18:56 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +	wrapper::Add<Cmd_BXT_Disable_V_Sync, Handler<>>("bxt_disable_v_sync");
```suggestion
	wrapper::Add<Cmd_BXT_Disable_VSync, Handler<>>("bxt_disable_vsync");
```

2023-02-18 16:36 UTC, SmileyAG commented
> Does this also work on Steam builds?

It does, but it would overriden after changing value in `gl_vsync` cvar anyway, so I don't think it there any sense to use it in Steam.

2023-02-18 17:32 UTC, YaLTeR commented on README.md
> +- **BXT_DISABLE_VSYNC** - if set, disables the V-Sync on initialization.
```suggestion
- **BXT_DISABLE_VSYNC** - if set, disables the V-Sync on initialization (Windows-only).
```

2023-02-18 17:41 UTC, merged

2023-02-18 17:41 UTC, YaLTeR commented
Thanks