Advanced checkpoints
YaLTeR/BunnymodXT pull request #468
Opened 2023-11-27 21:24 UTC by SmileyAG

https://github.com/YaLTeR/BunnymodXT/pull/459#issuecomment-1815195253

@khanghugo would like to know your response about that, since I really liked the idea you bring, but the impelementation was so limited at the start, so I decided to modernize it

2023-11-28 10:02 UTC, YaLTeR requested changes

2023-11-28 10:02 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +		hw.ORIG_Cbuf_AddText(ss.str().c_str());
I'd rather call the handler directly than go through the entire commandline machinery.

2023-11-29 04:20 UTC, khanghugo commented
Personally, I think the checkpoint previous might be the best addition here.

I am only playing KZ so that's my experience so far. When I play, I sometimes make the wrong checkpoint and that is used (very frequent). There is another case where I go check after landing the jump, so I have to "undo go check". It is nice to have. 

One quirk with using checkpoint in my case is that I will spam the checkpoint.

What I had in mind when I made this is to do map checking. Having check point helps with saving the best setup I have for some jumps to reliably do it over and over. This is where the spamming comes in. I have to stand at the very edge some times and so I have to spam check point create. For that, I think the previous check might be useful because I can check multiple jumps at the same time (obviously after getting a jump done). For normal gameplay, as I mentioned, that one more extra feature might be nice to have. The rest you have in the PR seems very overkill and personally I don't think I will find them that useful.

2023-11-29 04:58 UTC, SmileyAG commented
> Personally, I think the checkpoint previous might be the best addition here.
For normal gameplay, as I mentioned, that one more extra feature might be nice to have. The rest you have in the PR seems very overkill and personally I don't think I will find them that useful.

As the person who dedicated more than thousand hours at HLKZ, I wouldn't call `_goto`, `_remove`, `_reset` and `_next` cmds as overkill 

Because there is always practice when you want to make multiple checkpoints of same place, but with different velocity or bhop patterns in order to find out the best route for yourself

Like:
- Quickly switch between checkpoints with `_next` and `_prev` cmds
- Checkpoint that have a wrong velocity or bhop pattern could be erase with `_remove` command by specifying ID of that checkpoint
- To clear previous checkpoints and start the new series (e.g. for new map ) we could to use `_reset` command
- `_goto` could be used if I want to re-check to see if I might do better or find new route from that specific checkpoint, and if so, then I would to redo all checkpoints that go after that

I'd also started to think that it might be cool to add `bxt_ch_checkpoint_remove_after <id>`, there is use case for it:

Imagine that I have about 11 checkpoints, but everything that I done after 8th checkpoint is bad (due of missed skip, less velocity gained before, bad bhop pattern or some other reason)
So, I could type `bxt_ch_checkpoint_remove_after 8`, and it will erase all checkpoints that goes after 8th! (9, 10, 11)

2023-11-30 06:36 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +			}
Add a print in an else case too I guess saying that the id is invalid

2024-03-02 06:38 UTC, khanghugo commented
After using the normal checkpoint for a while, this starts to look appealing. I find myself playing movement modes in single player a lot and having this is very nice.

2024-03-03 02:07 UTC, SmileyAG commented
I don’t see anything else that could be changed, so this request is ready to be accepted, @YaLTeR

2024-03-07 05:21 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +	USAGE("Usage: bxt_ch_checkpoint_create\nCreates the checkpoint.\n");
```suggestion
	USAGE("Usage: bxt_ch_checkpoint_create\n Creates the checkpoint.\n");
```

2024-03-07 05:21 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +	USAGE("Usage: bxt_ch_checkpoint_current\nGo to current checkpoint.\n");
```suggestion
	USAGE("Usage: bxt_ch_checkpoint_current\n Go to current checkpoint.\n");
```

2024-03-07 05:21 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +	USAGE("Usage: bxt_ch_checkpoint_reset\nReset the checkpoints.\n");
```suggestion
	USAGE("Usage: bxt_ch_checkpoint_reset\n Reset the checkpoints.\n");
```

2024-03-07 05:21 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +	USAGE("Usage: bxt_ch_checkpoint_remove_after [id]\nDeletes the checkpoints following id.\n");
```suggestion
	USAGE("Usage: bxt_ch_checkpoint_remove_after [id]\n Deletes the checkpoints following id.\n");
```

2024-03-07 05:21 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +	USAGE("Usage: bxt_ch_checkpoint_next\nGo to the next checkpoint.\n");
```suggestion
	USAGE("Usage: bxt_ch_checkpoint_next\n Go to the next checkpoint.\n");
```

2024-03-07 05:21 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +	USAGE("Usage: bxt_ch_checkpoint_prev\nGo to the previous checkpoint\n");
```suggestion
	USAGE("Usage: bxt_ch_checkpoint_prev\n Go to the previous checkpoint\n");
```

2024-03-07 05:21 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +				hw.ORIG_Con_Printf("Not possible go to the previous checkpoint, since there are less than two of them!\n");
```suggestion
				hw.ORIG_Con_Printf("Not possible go to the previous checkpoint, since the current checkpoint is the first one!\n");
```

2024-03-07 05:24 UTC, YaLTeR approved these changes

2024-03-07 05:26 UTC, merged

2024-03-07 05:26 UTC, YaLTeR commented
Thanks!