Added bxt_get_steamid_from_demo
YaLTeR/BunnymodXT pull request #469
Opened 2023-11-28 01:55 UTC by SmileyAG

I know that there is `uint64_t`, but I decided to took from HLSDK to keep the same behaviour (for case if `uint64_t` on some other compiler will go for the fancy-schmancy stuff): https://github.com/ValveSoftware/halflife/blob/de70fada5061965884492178a7d6166646424a4e/public/steam/steamtypes.h

That const is not something that I got fantasied out of mind, most of Steam-related and demo parsing tools in fact uses the same magic number that is actually the starting ID

2023-11-28 10:10 UTC, YaLTeR requested changes
> I know that there is uint64_t, but I decided to took from HLSDK to keep the same behaviour (for case if uint64_t is differs on some other platform and it will go for the fancy-schmancy stuff)

Could you please just use `uint64_t`? The entire point of a type like this that it is the exact same on all platforms. If it turns out that at Valve this is not the case then call the alias something else because at that point it most certainly does not qualify to be called "uint64".

2023-11-28 10:10 UTC, YaLTeR commented on HLSDK/common/com_model.h
> +	uint64	m_nSteamID;
Are these fields only available on the Steam engines? Would be good to add a comment.

2023-11-28 10:10 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.hpp
> +	inline bool IsPlayingbackDemo() const { return demoplayback && *demoplayback == 1; }
```suggestion
	inline bool IsPlayingDemo() const { return demoplayback && *demoplayback == 1; }
```

2023-11-28 10:10 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +			hw.ORIG_Con_Printf(ss.str().c_str());
```suggestion
			hw.ORIG_Con_Printf("SteamID64: %" PRIu64 "\n", STEAMID32_TO_64);
```

2023-11-29 01:30 UTC, SmileyAG commented on HLSDK/common/com_model.h
> +	uint64	m_nSteamID;
Can confirm that starting from 4554 build - `m_nSteamID` field exists.

2023-11-29 01:32 UTC, SmileyAG commented on BunnymodXT/modules/HwDLL.hpp
> +	inline bool IsPlayingbackDemo() const { return demoplayback && *demoplayback == 1; }
https://github.com/YaLTeR/BunnymodXT/blob/89595432c52fcf01f5339f94b56cab1a986bbf88/HLSDK/common/demo_api.h#L23-L24

2023-11-29 01:43 UTC, SmileyAG commented on BunnymodXT/modules/HwDLL.cpp
> +			hw.ORIG_Con_Printf(ss.str().c_str());
Let me tell you a little backstory behind that: yes, I tried to pass it directly but the output value was a totally different (the format and types is still being the same)

And in one moment I got the idea in mind: *what if I simply pass that value as string instead*? And... that really started to output a right value!

Casting `STEAMID32` from **unsigned long long** to **unsigned long** also helped to solve that issue

2023-11-29 02:18 UTC, SmileyAG commented
> then call the alias something else because at that point it most certainly does not qualify to be called "uint64".

What you'd like to prefer from next ones? `steam_uint64`, `valve_uint64`, `uint64_steam`, `uint64_valve`, `S_uint64` or `V_uint64`? (the last two is got from idea that Quake developers re-implemented standard functions as `strcmp` at their own and named it starting with `Q_` prefix and GoldSrc code still refers to them in quite a half of functions)

Jokes aside, I could also accept for changing to `uint64_t` since that really not a big deal for implement at our own, so I leave the decision up to you

2023-11-29 04:57 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +			hw.ORIG_Con_Printf(ss.str().c_str());
That is quite strange.

2023-11-29 04:57 UTC, YaLTeR commented
> What you'd like to prefer from next ones?

Could you maybe just call it `steamid_t` or something

2023-11-30 06:30 UTC, merged

2023-11-30 06:30 UTC, YaLTeR commented
Thanks