Pattern-less implementation of GiveNamedItem function from HLSDK
YaLTeR/BunnymodXT pull request #471
Opened 2023-11-30 03:36 UTC by SmileyAG

That planned for partially support of the co-op, so that you can give the needed weapons to players without having to hook `GiveNamedItem` for the each specific mod

Code from HLSDK: https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/dlls/player.cpp#L3322

If you want to test, then for example you can add the following code to the **ClientCommand** function and then type `bxt_give weapon_shotgun` in console

```cpp
} else if ((std::strcmp(cmd, "bxt_give") == 0) && CVars::sv_cheats.GetBool()) {
		int iszItem = pEngfuncs->pfnAllocString(pEngfuncs->pfnCmd_Argv(1)); // Make a copy of the classname
		GiveNamedItem(pev, iszItem);
```

2023-11-30 06:32 UTC, YaLTeR requested changes

2023-11-30 06:32 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +			#define ALERT(at, format, ...) pEngfuncs->pfnAlertMessage(at, const_cast<char*>(format), ##__VA_ARGS__)
Just write it inline, no point in defining for 1 line

2023-11-30 08:32 UTC, chinese-soup commented on BunnymodXT/modules/ServerDLL.cpp
> +			#define ALERT(at, format, ...) pEngfuncs->pfnAlertMessage(at, const_cast<char*>(format), ##__VA_ARGS__)
https://github.com/YaLTeR/BunnymodXT/blame/d0d183a4f29d1f6f1c8a413dae132bca586df978/BunnymodXT/modules/ServerDLL.cpp#L1919

:-)

2023-11-30 08:34 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +			#define ALERT(at, format, ...) pEngfuncs->pfnAlertMessage(at, const_cast<char*>(format), ##__VA_ARGS__)
![image](https://github.com/YaLTeR/BunnymodXT/assets/1794388/993795e7-da91-4c5c-918c-f96cf4b7ab8d)

![image](https://github.com/YaLTeR/BunnymodXT/assets/1794388/f58f38bc-76aa-4a88-8a5a-d5c590285b54)

2023-11-30 09:57 UTC, chinese-soup commented on BunnymodXT/modules/ServerDLL.cpp
> +			#define ALERT(at, format, ...) pEngfuncs->pfnAlertMessage(at, const_cast<char*>(format), ##__VA_ARGS__)
Cool my passive aggressive man, but my point was that this code is also in ServerDLL.cpp, so it can be defined at the top of ServerDLL.cpp?

2023-11-30 09:58 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +			#define ALERT(at, format, ...) pEngfuncs->pfnAlertMessage(at, const_cast<char*>(format), ##__VA_ARGS__)
Yeah it could

2024-03-03 02:04 UTC, SmileyAG commented
I slightly changed the concept of this request. `bxt_give` command has been added that uses this our custom code, so that it is now possible to give weapons without searching for patterns for each mod, so all **CBasePlayer::GiveNamedItem** hooks have been removed and therefore `give` is no longer handled in the code either

I personally have nothing more to contribute to this request, so it is ready to be accepted, @YaLTeR

2024-03-07 05:40 UTC, YaLTeR approved these changes

2024-03-07 05:40 UTC, merged

2024-03-07 05:40 UTC, YaLTeR commented
Thanks!