Add bxt_ch_trigger_tp_keeps_momentum
YaLTeR/BunnymodXT pull request #502
Opened 2024-02-09 02:45 UTC by khanghugo

This is useful for some surf/bhop maps that take advantage of portal-like teleportation.

Implementation is simple because in order for it to work, the mapper has to make the map linear as well.

This case is promised to never happen.
![image](https://github.com/YaLTeR/BunnymodXT/assets/29143195/40b6a5da-181c-41ef-a904-bb53a8c33ee7)

Waiting for CI to test on Windows.

2024-02-09 05:30 UTC, SmileyAG commented
Do you want to know what the main issue with the that implementation? The fact is that your speed needs to be redirected depending on your direction

The angles must be taken either from those specified in `info_teleport_destination` (the mapper must take care of this so that it specify the correct angles) or redirected from the player angles at the worst

Take a look to that implementation and description: https://github.com/fireblizzard/agmod/pull/11

2024-02-09 05:37 UTC, khanghugo commented
Right, then there should be two options for it. With redirect and without it. Redirect is nice but I mean to have this for big surf maps and they are guaranteed to be built like that.

This is an example of a map that only works without redirect.

https://www.youtube.com/watch?v=s6Y5BY6-iGY

I can add both of that.

2024-02-09 06:51 UTC, SmileyAG requested changes

2024-02-09 06:51 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	auto pf = reinterpret_cast<CBaseEntity__IsPlayer_Linux*>(*reinterpret_cast<uintptr_t **>(vtable + 0xa0)); // 0x28 * 4
It is not efficient to hooking that type of function for each specific mod, since it can be implemented at own side:

```cpp
entvars_t* pev = *reinterpret_cast<entvars_t**>(reinterpret_cast<uintptr_t>(thisptr) + 4);
if (IsPlayer(pev->pContainingEntity))
```

```cpp
bool ServerDLL::IsPlayer(edict_t *ent)
{
	// https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/dlls/player.cpp#L2850

	auto &hw = HwDLL::GetInstance();

	if (strcmp(hw.GetString(ent->v.classname), "player") != 0)
		return false;

	if (!(ent->v.flags & FL_CLIENT))
		return false;

	if (pEngfuncs && hw.ppGlobals)
	{
		int index = pEngfuncs->pfnIndexOfEdict(ent);

		if ((index < 1) || (index > hw.ppGlobals->maxClients)) // gGlobalVariables.maxClients = svs.maxclients
			return false;
	}

	return true;
}
```

2024-02-09 16:59 UTC, khanghugo commented
Thanks for the help. This should be good. I don't have redirect option on by default because I think maps that take advantage of this are linear.

2024-02-11 18:26 UTC, SmileyAG requested changes

2024-02-11 18:26 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (pev) {
I suppose you should save and restore `pev->angles` and `pev->basevelocity`, since both of them is also reset by that function

2024-03-07 05:31 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +			pev->fixangle = 0; // cannot change angle if it is 1
When is this 1? Maybe we don't need to change angle if it's 1?

2024-03-07 05:31 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +		prev_view = pev->v_angle;
Why does this do less things than the Windows hook?

Also it's complex enough; maybe worth extracting to a common function.

2024-03-07 05:55 UTC, khanghugo commented on BunnymodXT/modules/ServerDLL.cpp
> +			pev->fixangle = 0; // cannot change angle if it is 1
I think something going on with all of the inheritance thing so it is hard for me to track but if `pev->fixangle = 1` then when I change the angles with following lines they don't work. If I set it back to `1` after changing the angle, doesn't work either. So it has to be `0` throughout that process.

2024-03-07 05:56 UTC, khanghugo commented on BunnymodXT/modules/ServerDLL.cpp
> +		prev_view = pev->v_angle;
i forgo :skull:

2024-03-07 06:02 UTC, khanghugo commented on BunnymodXT/modules/ServerDLL.cpp
> +			pev->fixangle = 0; // cannot change angle if it is 1
Hmm, so the `fixangle` is handled by the engine, not the game code. In `SV_RunCmd`, it won't update the player angle if that is the case and will set it back to 0 afterward.

2024-03-13 03:49 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +			pev->fixangle = 0; // cannot change angle if it is 1
So, when is this 1 in-game? Maybe when it is 1 we should not change the angle, instead of forcing it to 0 and changing the angle?

2024-03-13 03:54 UTC, khanghugo commented on BunnymodXT/modules/ServerDLL.cpp
> +			pev->fixangle = 0; // cannot change angle if it is 1
IIRC in teleport touch, hlsdk uses something else to change player viewangles and set this to 1. It is only set to 1 for teleport touch.

2024-03-13 03:57 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +			pev->fixangle = 0; // cannot change angle if it is 1
Oh, I see

2024-03-13 03:57 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +			pev->fixangle = 0; // cannot change angle if it is 1
Can you add that to the comment in the code please?

2024-07-12 17:55 UTC, merged

2024-07-12 17:55 UTC, YaLTeR commented
Thanks