bxt_enable_big_map: also big velocity
YaLTeR/BunnymodXT pull request #506
Opened 2024-02-21 04:50 UTC by khanghugo

Someone told me that they lag when going too fast. Current delta only supports +-4096. I make it +-8192. I think anything bigger than that is very impractical.

2024-02-21 12:48 UTC, SmileyAG requested changes

2024-02-21 12:48 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	auto max_velocity = CVars::sv_maxvelocity.GetFloat();
Can you do this in exactly the same way as with `map_size`?

That mean to specify this when calling a function in the arguments, it gives more flexibility of use for different code

2024-03-07 05:36 UTC, YaLTeR approved these changes

2024-03-07 05:36 UTC, merged

2024-03-07 05:36 UTC, YaLTeR commented
Thanks