Add bxt_ch_noclip_speed
YaLTeR/BunnymodXT pull request #507
Opened 2024-02-21 06:13 UTC by khanghugo

Closes #505 

By default noclip is now faster. I think it is nicer that it is faster now. Could be changed.

Also the speed here is just rough estimation because if player has very high forward/side/up speed, then they will go fast. What are the odds.

Might break existing Noclip% WR.

2024-02-21 12:44 UTC, SmileyAG requested changes

2024-02-21 12:44 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (hw.noclip_anglehack && *hw.noclip_anglehack) {
```cpp
offMovetype = 0xDC;
```

```cpp
int *movetype = reinterpret_cast<int*>(pmove + offMovetype);
if (*movetype == MOVETYPE_NOCLIP) {
```

I'm going to remove declarations of `noclip_anglehack` once I touch the BXT code again, because it's actually not needed to be honest, it just takes extra time to find it for each build, **MOVETYPE_NOCLIP** check would be better even

2024-03-07 05:35 UTC, YaLTeR commented
> By default noclip is now faster.

Tbh, considering noclip% is a thing (even if a meme), I think by default it should not change the speed. Especially since right now it's not clear how to restore the default behavior. Could you add like an _enabled cvar too?

2024-03-07 05:57 UTC, khanghugo commented
ye

2024-07-11 22:43 UTC, khanghugo commented
This one has the suggested changes but I squashed all the commits.

2024-07-12 14:11 UTC, YaLTeR commented
Weird hlstrafe commit needs to be removed, otherwise good to go

2024-07-12 14:12 UTC, YaLTeR approved these changes

2024-07-12 17:19 UTC, YaLTeR commented
And I guess resolve conflict

2024-07-12 17:21 UTC, khanghugo commented
There is no conflict here.

2024-07-12 17:29 UTC, merged

2024-07-12 17:29 UTC, YaLTeR commented
Thanks