Warn if Metamod is detected. Auto disable it for cstrike.
YaLTeR/BunnymodXT pull request #508
Opened 2024-02-21 18:21 UTC by khanghugo

"Warn" in here means exiting the game right away. I am not sure how to do it more elegantly.

2024-02-22 04:17 UTC, khanghugo commented
Hmmm, it doesn't work on Windows. I keep getting error.
![image](https://github.com/YaLTeR/BunnymodXT/assets/29143195/098e0e49-e96d-4db8-912e-8131faf3f93d)

String manipulation in C++ is fairly arcane for me.

2024-02-25 16:53 UTC, SmileyAG commented
> Hmmm, it doesn't work on Windows. I keep getting error.
> 
> String manipulation in C++ is fairly arcane for me.

Well, the crucial issue with this code is actually not how you did the string manipulation, but how you declared the functions

You can only use `__fastcall` if you declare a member functions for **Windows** (e.g. *CBasePlayer::TakeDamage*)
In all other majority of cases, `__cdecl` will be your choice

Also, when you use `__fastcall`, you will need to specify **int edx** as the second parameter
**edx** doesn't seem to be used, so you can return any value to it (e.g. `0`) in case you need to call that function

Examples:

```cpp
HOOK_DECL(void, __cdecl, PM_PreventMegaBunnyJumping) // Windows, Linux

typedef void(__fastcall *_CBasePlayer__GiveNamedItem)(void *thisptr, int edx, const char *pszName); // Windows
_CBasePlayer__GiveNamedItem ORIG_CBasePlayer__GiveNamedItem;
typedef void(__cdecl *_CBasePlayer__GiveNamedItem_Linux)(void *thisptr, const char *pszName); // Linux
_CBasePlayer__GiveNamedItem_Linux ORIG_CBasePlayer__GiveNamedItem_Linux;
```

```cpp
#ifdef _WIN32
ORIG_CBasePlayer__GiveNamedItem(classPtr, 0, HwDLL::GetInstance().GetString(iszItem));
#else
ORIG_CBasePlayer__GiveNamedItem_Linux(classPtr, HwDLL::GetInstance().GetString(iszItem));
#endif
```

2024-02-25 16:56 UTC, SmileyAG commented
I also made a pull request with the necessary changes to that branch: https://github.com/khanghugo/BunnymodXT/pull/4

2024-02-25 23:38 UTC, khanghugo commented
Thanks. Looking good.

2024-03-03 01:51 UTC, SmileyAG approved these changes

2024-03-07 05:13 UTC, YaLTeR requested changes

2024-03-07 05:13 UTC, YaLTeR commented on BunnymodXT/helper_functions.cpp
> +		str = std::regex_replace(str, std::regex("/"), "\\");
Does this really need a regex for a single character? Can this maybe use `std::replace`?

2024-03-07 05:13 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +	if (boost::ends_with(szDllFilename, helper_functions::add_os_library_extension("metamod").c_str()))
I can't look at these two (three?) allocations (one for converting "metamod" to std::string, second for allocating the return std::string from add_os_library_extension, third for converting ".dll" to std::string) with a straight face. Maybe do something like

```
#ifdef _WIN32
#define DLL_EXTENSION ".dll"
#else
#define DLL_EXTENSION ".so"
#endif
```

in that header, then `boost::ends_with(szDllFilename, "metamod" DLL_EXTENSION)`? Since you can concatenate constexpr strings like that.

2024-03-07 05:13 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +		EngineDevMsg("[hw dll] AmxModX detected.\n");
Is it more intuitive to say AmxModX here instead of Metamod?

2024-03-07 05:13 UTC, YaLTeR commented on BunnymodXT/helper_functions.cpp
> +		new_path = filename.substr(0, index) + add_os_library_extension(new_lib_path).c_str();
Here's a fun C++ question, does the std::string returned from `add_os_library_extension(new_lib_path)` live long enough for this to be safe? Or is it deallocated right after the call to `c_str()` but before the call to `+` so it's actually broken?

2024-03-07 05:13 UTC, YaLTeR commented on BunnymodXT/helper_functions.cpp
> +		HwDLL::GetInstance().ppGlobals = nullptr;
Certainly an original way to cause a crash. Maybe `std::exit`?

2024-03-07 05:13 UTC, YaLTeR commented on BunnymodXT/helper_functions.cpp
> +		const auto index = filename.find(start);
What if it's not found? I.e. ppl put metamod somewhere other than `addons`.

2024-03-08 02:53 UTC, khanghugo commented
Eh, I wouldn't know really. @SmileyAG can explain that.

2024-03-10 14:57 UTC, SmileyAG commented
Made appropriate changes from reviews.

And I handled most of edge cases for that request, but let know if I missed something more, he-he.

2024-03-13 03:57 UTC, YaLTeR commented on BunnymodXT/helper_functions.cpp
> +		const std::string filename = current_lib_path;
This already allocates unconditionally; might as well just return the `std::string`? That'll also get rid of the awkward static string.

2024-03-13 03:57 UTC, YaLTeR commented on BunnymodXT/helper_functions.cpp
> +		com_fixslashes(new_lib_path);
I'm not sure that's needed; you already pass the right slashed version at the call site.

2024-03-13 03:57 UTC, YaLTeR commented on BunnymodXT/helper_functions.hpp
> +	#endif
Defines cannot be scoped, so this looks a little misleading. Please move above the namespace.

2024-03-13 03:57 UTC, YaLTeR commented on BunnymodXT/stdafx.hpp
> +#include <regex>
No longer needed
```suggestion
```

2024-03-13 05:06 UTC, SmileyAG commented on BunnymodXT/helper_functions.cpp
> +		com_fixslashes(new_lib_path);
Well, you know, in this particular case the names of the libraries were different (win: `mp.dll`, linux: `cs.so`), so in this case you are right

But what if next time I want to type the path to a library that has the same name on both platforms, and I don't want to duplicate code with using preprocessor flags only to manually change the type of slashes?

So let this function do it for us instead

2024-03-13 08:25 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +			szDllFilename = helper_functions::swap_lib(szDllFilename, cs_lib, "addons").c_str();
This deallocates the returned string right away; the c_str() becomes invalid. You need to store it somewhere on the stack where it will be alive while it is used.

2024-03-13 16:05 UTC, YaLTeR commented on BunnymodXT/modules/HwDLL.cpp
> +			const char *swap_lib_output = helper_functions::swap_lib(szDllFilename, cs_lib, "addons").c_str();
This suffers from the same problem

2024-03-15 07:07 UTC, YaLTeR approved these changes
Just to be sure @khanghugo could you test this still works on Linux?

2024-03-15 22:58 UTC, khanghugo commented
Works for me.

2024-03-16 03:51 UTC, merged

2024-03-16 03:51 UTC, YaLTeR commented
Thanks