feature: landmark for trigger_teleport
YaLTeR/BunnymodXT pull request #510
Opened 2024-02-26 18:21 UTC by khanghugo

Something from CSS. Something like this https://github.com/s1lentq/ReGameDLL_CS/issues/950

~~I have to hijack the "message" field because `trigger_teleportation` does not have its own key value function.~~

~~I don't really hope this thing is merged but I want it stay around in case anyone wanting to test~~ landmark teleportation in GoldSrc. It is a neat feature, very simple and effective.

Here is the map to test, along with its source 
[arte_confused.zip](https://github.com/YaLTeR/BunnymodXT/files/14409237/arte_confused.zip)

2024-03-03 05:28 UTC, khanghugo commented
The only reason why I say that "I don't really hope this thing is merged" because the implementation is very constrained. I cannot really think of a way to make maps taking advantage of this to just work. That means mappers must be aware of BXT to add value into "message" field or somebody else has to edit the map with bspguy or something. Also simply hijacking the "message" field is not very nice (attitude).

2024-03-04 18:25 UTC, SmileyAG commented
> That means mappers must be aware of BXT to add value into "message" field or somebody else has to edit the map with bspguy or something.

I suppose `DispatchKeyValue` function can be hooked from exported table (`funcs.pfnKeyValue`) for hijacking keyvalues:
https://github.com/YaLTeR/BunnymodXT/blob/a0cc46992a10612e1253d4ac2b146babbf383438/HLSDK/engine/eiface.h#L424

Then perform all needed conditions, if result is positive then received edict and its keyvalue we can store all in our custom container at the same index (e.g. `std::vector` with `emplace_back`)

https://github.com/YaLTeR/BunnymodXT/blob/a0cc46992a10612e1253d4ac2b146babbf383438/HLSDK/engine/eiface.h#L297-L304

In our function we can iterate over that container and check whether the `szKeyName` matches with what you expect and whether the edict from the same index in the container matches the one edict you are checking for
If all matches, then extract data from `szValue` and apply it in your code

In the end, clean the container every time the server is shutdown (`ServerDeactivate` function should be ideal for this task, it is also exported by using `funcs.pfnServerDeactivate`):
https://github.com/YaLTeR/BunnymodXT/blob/a0cc46992a10612e1253d4ac2b146babbf383438/HLSDK/engine/eiface.h#L446-L448

2024-03-27 00:45 UTC, khanghugo commented
Thanks for the suggestion, I think this should be better.

2024-03-28 11:54 UTC, SmileyAG requested changes

2024-03-28 11:54 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (pkvd && pentKeyvalue
```cpp
	if (pkvd && pentKeyvalue && pkvd->szClassName && pkvd->szKeyName && pkvd->szValue)
	{
		if (!strcmp(pkvd->szClassName, "trigger_teleport") && !strcmp(pkvd->szKeyName, "landmark"))
		{
			const auto index = pEngfuncs->pfnIndexOfEdict(pentKeyvalue);
			tpLandmarks[index] = pkvd->szValue;
		}
	}
```

2024-03-28 11:54 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +		pkvd->fHandled = 1;
Don't set `pkvd->fHandled = 1`!

Because in some game it may turn out that in the KeyValue function of the corresponding class this case will be handled, then you simply will not allow the game to read data from it, I think the consequences are not worth explaining

I think we should add the following comment at the beginning of the function:

```cpp
// Don't set pkvd->fHandled = 1, as some games could handle the same cases for the same entities, which means you won't give the game a chance to read that data!
```

2024-03-28 11:54 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +std::tuple<bool, Vector> TriggerTpLandmarkBefore(bool work, entvars_t *this_pev, entvars_t *pev, enginefuncs_t *pEngfuncs)
```cpp
std::tuple<bool, Vector> TriggerTpLandmarkBefore(bool enabled, entvars_t *this_pev, entvars_t *pev)
```

2024-03-28 11:54 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (is_duck)
```cpp
const Vector VEC_HULL_MIN(-16, -16, -36);
const Vector VEC_DUCK_HULL_MIN(-16, -16, -18);
auto hull_offset = is_duck ? VEC_DUCK_HULL_MIN : VEC_HULL_MIN;

pev->origin[2] += hull_offset[2];
```

https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/dlls/util.h#L414-L424

2024-03-28 11:54 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	auto available = true;
```cpp
if (HwDLL::GetInstance().IsValidEdict(landmark))
	return std::make_tuple(true, Vector(pev->origin) - Vector(landmark->v.origin));
```

2024-03-28 11:54 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	auto what = tpLandmarks.at(index);
```cpp
auto landmarkName = tpLandmarks.at(index);
edict_t *landmark = ServerDLL::GetInstance().pEngfuncs->pfnFindEntityByString(NULL, "targetname", landmarkName.c_str());
```

2024-03-28 11:54 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +void TriggerTpKeepsMomentumRestore(Vector prev_vel, Vector prev_view, Vector prev_angles, Vector prev_basevelocity, entvars_t *pev, enginefuncs_t *pEngfuncs)
```cpp
void TriggerTpKeepsMomentumRestore(entvars_t *pev, Vector prev_vel, Vector prev_view, Vector prev_angles, Vector prev_basevelocity)
```

2024-03-28 11:54 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	edict_t *edicts;
```cpp
const auto index = ServerDLL::GetInstance().pEngfuncs->pfnIndexOfEdict(this_pev->pContainingEntity);
```

2024-03-28 11:54 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +			pEngfuncs->pfnAngleVectors(vecAngles, vecForward, nullptr, nullptr);
```cpp
ServerDLL::GetInstance().pEngfuncs->pfnAngleVectors(vecAngles, vecForward, nullptr, nullptr);
```

2024-03-28 11:54 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	EngineDevWarning("enabled %d pEngfuncs is %d\n", is_bxt_ch_trigger_tp_landmark_enabled, pEngfuncs == NULL);
Remove those debug warnings.

2024-03-28 11:54 UTC, SmileyAG commented
> Apparently this does not work on Windows atm. Not sure why.

The reason why it does not work on Windows is because the hook was not declared in the `MemUtils::Intercept` and `MemUtils::RemoveInterception` blocks

https://github.com/YaLTeR/BunnymodXT/blob/76aefb29543951ab4ef3eb90084d7add4f098f88/BunnymodXT/modules/ServerDLL.cpp#L128
https://github.com/YaLTeR/BunnymodXT/blob/76aefb29543951ab4ef3eb90084d7add4f098f88/BunnymodXT/modules/ServerDLL.cpp#L183

2024-03-28 13:01 UTC, SmileyAG commented on BunnymodXT/modules/HwDLL.cpp
> +		ServerDLL::GetInstance().ClearTPLandmarks();
Ugh. You know, clearing in `SV_SpawnServer` is generally not bad, because it is called when a new map starts, changelevels and similar events, and it is called before the engine calls `DispatchKeyValue`

`ServerDeactivate` (**funcs.pfnServerDeactivate** from `DLL_FUNCTIONS` table) is also called in those events and also before `DispatchKeyValue`, but the difference is that it also covers other events such as disconnect
At that point clearing in `ServerDeactivate` looks a bit safer, because for example if you are disconnected and you are in the menu, you know that the data will already be cleared, and in the case of `SV_SpawnServer` you need load map to clear this old data

So personally, I would advise hooking `ServerDeactivate` from the server-side (fortunately it doesn’t require patterns) and including a comment at the beginning of its function about the difference in data cleanup compared to `SV_SpawnServer`

You may also need to hook `ServerActivate` to track its state, because HLSDK does this to avoid unnecessary calls to `ServerDeactivate`, take a look at the highlighted lines: https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/dlls/client.cpp#L685-L708
`ServerActivate` could be hooked from exported server table too, so not need to worries about patterns

2024-03-28 13:16 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	auto is_duck = pev->button & (IN_DUCK) || pev->flags & (FL_DUCKING);
Maybe this check should be next?

```cpp
auto is_duck = pev->bInDuck || pev->flags & (FL_DUCKING);
```

Because checking for a pressed key with `+duck` input does not look completely reliable
In some games, duck on the movement code side may be disabled, but the command for duck input is available in the game

`bInDuck` is set during the crouching process, and `FL_DUCKING` flag is set when we are definitely crouched

2024-03-29 02:36 UTC, khanghugo commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (is_duck)
So many repetition of this HULL values, maybe future refactor?

2024-03-29 02:42 UTC, khanghugo commented on BunnymodXT/modules/ServerDLL.cpp
> +void TriggerTpKeepsMomentumRestore(Vector prev_vel, Vector prev_view, Vector prev_angles, Vector prev_basevelocity, entvars_t *pev, enginefuncs_t *pEngfuncs)
This is rebase of another other commit, maybe ill change it there instead

2024-03-29 02:44 UTC, khanghugo commented on BunnymodXT/modules/ServerDLL.cpp
> +			pEngfuncs->pfnAngleVectors(vecAngles, vecForward, nullptr, nullptr);
Rebase of another commit

2024-03-29 02:47 UTC, khanghugo commented on BunnymodXT/modules/ServerDLL.cpp
> +	auto is_duck = pev->button & (IN_DUCK) || pev->flags & (FL_DUCKING);
Eh, I am not sure what else to check here for duck beside those two. On top of that, the condition for landmark tp to work is very involving and the mapper (or map editor) has to allow it to happen. It is possible that a different game mod will implement this inside their game mod already without relying on this.

2024-03-29 02:54 UTC, khanghugo commented on BunnymodXT/modules/HwDLL.cpp
> +		ServerDLL::GetInstance().ClearTPLandmarks();
What do you mean by tracking `ServerActivate` state? Tracking `g_serveractive`? So there needs to be either another pattern for that static value or BXT own static value for `g_serveractive`? Seems like a lot of extra work.  I think clearing data on load is fine unless you are adamant about it then I can make some changes for that.

2024-03-29 02:56 UTC, SmileyAG commented on BunnymodXT/modules/ServerDLL.cpp
> +	if (is_duck)
> So many repetition of this HULL values, maybe future refactor?

Surely.

I know that now in the code these HULL values are declared several times in scope of different functions, but with a future refactor all this will be declared once in some header.

So let it be like this for now.

2024-03-29 03:12 UTC, SmileyAG commented on BunnymodXT/modules/HwDLL.cpp
> +		ServerDLL::GetInstance().ClearTPLandmarks();
If you read the highlighted lines carefully, you will understand that you don’t need to intercept that `g_serveractive` variable at all. Let me show you a concept of how this can be done without patterns.


```cpp
// Global variable
bool g_serveractive = false;

// Find "DLL_FUNCTIONS funcs;" in the server module for the declaration location
ORIG_ServerActivate = funcs.pfnServerActivate;
ORIG_ServerDeactivate = funcs.pfnServerDeactivate;

HOOK_DEF_0(ServerDLL, void, __cdecl, ServerDeactivate)
{
	// https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/dlls/client.cpp#L685-L708
	if (g_serveractive)
	{
		g_serveractive = false;

		// Peform any shutdown operations here...
	}

	ORIG_ServerDeactivate();
}

HOOK_DEF_3(ServerDLL, void, __cdecl, ServerActivate, edict_t*, pEdictList, int, edictCount, int, clientMax)
{
	g_serveractive = true;
	ORIG_ServerActivate(pEdictList, edictCount, clientMax);
}
```

2024-03-29 03:19 UTC, SmileyAG commented on BunnymodXT/modules/HwDLL.cpp
> +		ServerDLL::GetInstance().ClearTPLandmarks();
> on load is fine unless you are adamant about it then I can make some changes for that.

Well I'd fine with it in general because I don't think there would a cases when you want to access that data while being not on the server, and even so there seems a validation checks is done, so I'd like to say fine, but `ServerDeactivate` would be a nicer option in fact, maybe it should be done with future refactoring then

2024-03-29 03:21 UTC, khanghugo commented on BunnymodXT/modules/HwDLL.cpp
> +		ServerDLL::GetInstance().ClearTPLandmarks();
I totally understood what you mean. I just wonder if it is worth it. Do you think it is good to pursue this?

2024-03-29 03:23 UTC, khanghugo commented on BunnymodXT/modules/HwDLL.cpp
> +		ServerDLL::GetInstance().ClearTPLandmarks();
Github going slow. I agree it should be in the future refactor. This PR is another rebase of another PR so I am not very confident to make some changes here.

2024-07-13 16:23 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +		&& !strcmp(pkvd->szKeyName, "landmark")
That's a lot of string comparisons that happen all the time (?), especially for an optional feature.

2024-07-13 16:23 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	auto is_duck = pev->button & (IN_DUCK) || pev->flags & (FL_DUCKING);
I have the same question as Smiley

2024-07-15 12:11 UTC, khanghugo commented on BunnymodXT/modules/ServerDLL.cpp
> +		&& !strcmp(pkvd->szKeyName, "landmark")
You made me paranoid so I debug print it. This is only called when a new server is started. Every time a new server is started, a lot of string comparisons like this happen to parse entities in BSP. This one is just one extra entity available in the game.

2024-07-27 09:48 UTC, YaLTeR approved these changes
Otherwise good to go ig

2024-07-27 09:48 UTC, YaLTeR commented on BunnymodXT/modules/ServerDLL.cpp
> +	const Vector VEC_DUCK_HULL_MIN(-16, -16, -18);
I don't have an update PR button for some reason, but this probably needs to be removed after rebase to master since they are now defines.

2024-07-27 19:03 UTC, merged

2024-07-27 19:03 UTC, YaLTeR commented
Thanks